### ISSUE TITLE
Pull requests languishing?

### ISSUE THREAD

**Issue by miketheman** [chef-boneyard/chef-web-docs-2016#109]
Hi @jamescott and other committers,

There's a bunch of open issues and pull requests sitting around here, not getting any love.

It's considered good form to at least comment on them, provide some feedback to the author as to why you have not yet merged in their contribution that they took the time to write.

If you need some help reviewing and validating these, by all means, ask for help. We're a community, and together we are strong.

-M

**Comment by jamescott** [comment]
Not really. Most of them have been addressed in some fashion (though not all of them) and many of these were addressed very quickly. I should, perhaps, be a bit more aggressive with closing them.

**Comment by jamescott** [comment]
OK. Got the list down to just a few pull requests and issues.

**Comment by miketheman** [comment]
Thanks @jamescott !
