### ISSUE TITLE
The directory resource page doesn't specify the default mode value

### ISSUE THREAD

**Issue by e0da** [chef-boneyard/chef-web-docs-2016#111]
If I 

``` ruby
directory MY_DIR do
  user USER
end
```

What is the mode? This is missing from the docs.

**Comment by jamescott** [comment]
Mode is an attribute of the directory resource: http://docs.opscode.com/resource_directory.html#attributes

If the file already exists, Chef will use the same mode value. If the file does not exist, Chef will pass a 0777, and then subtract the umask on the system to get the final value.

So there isn't really a specific "default" value.

**Comment by jamescott** [comment]
I updated the mode description to include a better description of what Chef does when mode isn't specified. Also here:

"The octal mode for a file. If `mode` is not specified and if the directory already exists, the existing mode on the directory is used. If `mode` is not specified, the directory does not exist, and the `:create` action is specified, the directory will be created according to the umask of the node on which the directory is to be created. For example, the default mode is often `0644` when the umask on the node is `022` (a common default value for the root user on many |unix| systems)."

Also, this behavior is going to change (slightly) with the impending release of Chef 11.6. The release notes will contain a short section on this change.

Hope this helps!

James

**Comment by jamescott** [comment]
(note above the 0777 in my first reply is related to the changes for Chef 11.6)

**Comment by jamescott** [comment]
OK, after some more discussion here, updated description for mode attribute. For the directory resource:

http://docs.opscode.com/resource_directory.html#attributes

and then for the File-based resources:

http://docs.opscode.com/resource_file.html#attributes

(which is the same for cookbook_file, file, remote_file, and template resources)

and then the release notes for 11.6 describe what will change:

http://docs.opscode.com/release_notes.html#updated-behavior-for-mode-attribute

**Comment by jamescott** [comment]
and that (hopefully) answers your initial question about what the default value for mode should be.

**Comment by e0da** [comment]
EXCELLENT! That all makes sense, and the documentation updates looks great. THANK YOU! :smile:
