### ISSUE TITLE
docs.opscode.com needs a link for reporting issues

### ISSUE THREAD

**Issue by zts** [chef-boneyard/chef-web-docs-2016#126]
When looking at the docs site, it is not obvious how to report problems with the content.  There is no obvious link to this repo on Github, nor any other advice on reporting issues (Github Issues?  Opscode Tickets?  Mailing list?)

As someone participating on IRC/mailing list,
When another user reports unclear/misleading information on the docs site,
I would like to be able to point them at a howto for reporting that problem.

**Comment by jamescott** [comment]
I added this page: http://docs.opscode.com/feedback.html that details the various ways to send feedback. The page has been there for while (~3 months, perhaps even added as a response to seeing this issue come through initially). Apologies for waiting so long to address this issue directly here.

James

**Comment by zts** [comment]
Thanks, James.  I'd suggest making the existence of the page more prominent (eg, a link in the footer of every page), but this certainly does give me something to point to.

Thankyou!

**Comment by jamescott** [comment]
Yeah, I've been playing around with the footers to get the copyright/versioning info in there. (Won that battle, yesterday.) I will investigate adding a "Send feedback to docs@opscode.com." string in there too.

**Comment by jamescott** [comment]
OK, this commit should add a string in the footer upon the next build for each of the docs collections:

https://github.com/opscode/chef-docs/commit/fd5c0286279452ffb02ef43ea310feff82f77336

Builds occur daily (even hourly) for the current versions: docs.opscode.com, docs.opscode.com/enterprise, and docs.opscode.com/open_source
