### ISSUE TITLE
windows_package LWRP documentation is missing options

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#134]
We have a page at http://docs.opscode.com/lwrp_windows.html that documents the windows_package resource, but it is missing some options with respect to the documentation on GitHub. The full list of supported attributes is:

```
    package_name: name attribute. The 'DisplayName' of the application installation package.
    source: The source of the windows installer. This can either be a URI or a local path.
    installer_type: They type of windows installation package. valid values are: :msi, :inno, :nsis, :wise, :installshield, :custom. If this value is not provided, the provider will do it's best to identify the installer type through introspection of the file.
    checksum: useful if source is remote, the SHA-256 checksum of the file--if the local file matches the checksum, Chef will not download it
    options: Additional options to pass the underlying installation command
    timeout: set a timeout for the package download (default 600 seconds)
    version: The version number of this package, as indicated by the 'DisplayVersion' value in one of the 'Uninstall' registry keys. If the given version number does equal the 'DisplayVersion' in the registry, the package will be installed.
    success_codes: set an array of possible successful installation return codes. Previously this was hardcoded, but certain MSIs may have a different return code, e.g. 3010 for reboot required. Must be an array, and defaults to [0, 42, 127].
```

**Comment by jamescott** [comment]
I updated the topic to include some context for the options attribute. How is this?

http://docs.opscode.com/lwrp_windows.html#windows-package

**Comment by juliandunn** [comment]
Hi @jamescott,

Looking good. Couple of comments:
- The idempotency guard for installed packages will look in _four_ registry keys actually; they are listed here in order: https://github.com/opscode-cookbooks/windows/blob/master/providers/package.rb#L184
- If "source" is a local file, it has to be expressed in URI form, since it uses `remote_file` under the hood. (e.g. "file:///C:/Users/Downloads/myinstaller.msi")
- Typo under `installer_type` description -- should be "quiet" not "quite"
- Missing quotes at the end of the msiexec command example.
- Could be a little clearer about how the options are used. `options "IACCEPTMSODBCSQLLICENSETERMS=YES"` means this will be passed directly to the msiexec command as `msiexec /qn /i c:\chef\cache\msodbcsql_64.msi IACCEPTMSODBCSQLLICENSETERMS=YES`. Right now the text is a little hand-wavy.
- The description for `timeout` mentions "seconds" twice; the second parenthetical is probably unnecessary.
- In the description for `version` I think you mean "If the version number equals the display version, the package will _not_ be installed." I read what the code does, and I think it's an error in the original README for the Windows cookbook.

Thanks James!

**Comment by jamescott** [comment]
Ah!

https://github.com/opscode/chef-docs/commit/4ac18faa3649154d81cfd4f0020f3ea13b25b1b4

**Comment by jamescott** [comment]
Updated: http://docs.opscode.com/lwrp_windows.html#windows-package
