### ISSUE TITLE
excess replacement crond with cron.d

### ISSUE THREAD

**Issue by d-higuchi** [chef-boneyard/chef-web-docs-2016#138]
in in swaps/swap_names.txt,

> .. |crond| replace:: cron.d

in step_resource/step_resource_service_use_variable.rst,

> The following example shows how to install |crond|
> how to install |crond| on various nodes
> the |crond| service on nodes

they "crond" are just "crond" program, not "cron.d" directory.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/52f1877c66ae30c3ab9c0f0db5150077e91303b3

**Comment by d-higuchi** [comment]
thanks!
