### ISSUE TITLE
Weird paragraph

### ISSUE THREAD

**Issue by jblaine** [chef-boneyard/chef-web-docs-2016#15]
This paragraph in https://github.com/opscode/chef-docs/blob/master/includes_repository/includes_repository.rst is odd to me. Seems out of place, too specific, and not suited to general documentation. It assumes the repository is on github, etc.

"The Chef repository can be cloned directly from github or it can be downloaded from github as a tar.gz file, and then associated with another version source control system, such as Subversion, Mercurial, or Bazaar."

**Comment by jblaine** [comment]
Also, you already cover this in a link from the page where that paragraph was found. It leads here:

http://docs.opscode.com/essentials_repository_create.html

**Comment by jblaine** [comment]
https://github.com/opscode/chef-docs/pull/16

**Comment by jamescott** [comment]
Hi Jeff,

What if those two sentences were combined, like this:

"The |chef| repository is located on a workstation and should be treated like source code. The |chef| repository can be cloned directly from |github| or it can be downloaded from |github| as a |tar gz| file, and then associated with another version source control system, such as |svn|, |mercurial|, or |bazaar|."

Thoughts?

James

**Comment by jblaine** [comment]
Hi James.

IMO, it's redundant and should really just be removed from that particular page (PR #16 above).

Somewhat separately, assuming you keep it, it is vague in that it refers to "THE chef repository can be cloned directly from..." (emphasis mine). It poses it as if there is only one canonical place to start from, but doesn't explain up front that you're talking about "the Opscode boilerplate chef repository" ... that most people clone for starters.

It's very Hosted-Chef-Customer-centric which doesn't seem right (my opinion) given that Chef is a lot more than just Hosted Chef.

Just my 2 opinionated cents!

**Comment by jamescott** [comment]
OK. Thanks Jeff. I will take the pull requests that you have suggested and merge them.

At some point, I intend to have Hosted-, Private-, and Open Source-specific docs so I'll save this revised paragraph stuff for the future.

James
