### ISSUE TITLE
directory resource ACL example is incorrect

### ISSUE THREAD

**Issue by lewisthompson** [chef-boneyard/chef-web-docs-2016#171]
In the examples at http://docs.opscode.com/resource_directory.html#windows-file-security the example:

```
rights :full_control, "user_name", option => :applies_to_children
```

should in fact be:

```
rights :full_control, "user_name", :applies_to_children => true
```

**Comment by juliandunn** [comment]
@jamescott The "option" hash is actually incorrect in its entirety ... have a look at https://github.com/opscode/chef/blob/master/lib/chef/mixin/securable.rb#L106 for the correct syntax

**Comment by jamescott** [comment]
Ah, so true! Good catch, and thanks. Fix posted to github: https://github.com/opscode/chef-docs/commit/99816aa952a45e823604020873afc780efd244f0 ... is building.
