### ISSUE TITLE
A number of typos on the "About Resources and Providers" page

### ISSUE THREAD

**Issue by jmcmahon** [chef-boneyard/chef-web-docs-2016#177]
See attached image for the typos.
![about resources and providers chef docs](https://f.cloud.github.com/assets/844169/1303226/7b3cb068-314b-11e3-8750-7fe0d1213161.jpg)

**Comment by jamescott** [comment]
Thanks for the comments! I have made the changes you suggested and rewrote the batch description to just take out a bunch of stuff.

https://github.com/opscode/chef-docs/commit/98c271617d679c2e988dde2a6b3223ce08b807f7
