### ISSUE TITLE
Duplicated paragraph on the "Manage the Hosted Chef Server" page

### ISSUE THREAD

**Issue by jmcmahon** [chef-boneyard/chef-web-docs-2016#178]
The first paragraph on the "Manage the Hosted Chef Server Page" is repeated.

http://docs.opscode.com/manage_server_hosted.html

See screenshot below.
![manage the hosted chef server chef docs](https://f.cloud.github.com/assets/844169/1306072/99e79958-31a8-11e3-98f8-a174e15c6f29.jpg)

**Comment by jamescott** [comment]
Ah, good eye. Double included files.

https://github.com/opscode/chef-docs/commit/dd2fcbaa4d404ed4748fe005ea5278f2d4323d32

These whole pages are going to change very soon because the server UI is being updated with a whole new design/layout.
