### ISSUE TITLE
Typos on the "Community Plugins: Ohai" page

### ISSUE THREAD

**Issue by jmcmahon** [chef-boneyard/chef-web-docs-2016#179]
There are a few typos on the "Community Plugins: Ohai" page. 

http://docs.opscode.com/community_plugin_ohai.html

See comments in screenshot below.
![community plugins- ohai chef docs](https://f.cloud.github.com/assets/844169/1306353/85b0f4ce-31ae-11e3-845d-00a73dfafb42.jpg)

**Comment by jamescott** [comment]
Updated, thanks again!

https://github.com/opscode/chef-docs/commit/7731bebc246662b3b2649090926406600d70fbc4
