### ISSUE TITLE
"Bootstrap a Node" page needs better description and examples for non-Ubuntu nodes

### ISSUE THREAD

**Issue by jmcmahon** [chef-boneyard/chef-web-docs-2016#180]
The "Bootstrap a Node" page borrows the description from the "About the Server" page. Consequently, the lead paragraph discusses a separate topic. This lead paragraph should be more tailored to the title.

The page also says that if you are using a non-Ubuntu OS for your node, you need to provide other info to the bootstrap command, but gives no examples or the proper syntax. The page should list what OSes are supported and the proper syntax,
![bootstrap a node chef docs](https://f.cloud.github.com/assets/844169/1306797/5a298c88-31b5-11e3-91df-fbfc82935a14.jpg)
 or point to a page that does.  

See attached screenshot and comments.

**Comment by jamescott** [comment]
Thanks again. I appreciate all of this feedback.

https://github.com/opscode/chef-docs/commit/b2d521584833b2bec005cb110466443f139a5baa

New intro. Pointed to the knife bootstrap / knife windows topics where the full descriptions of the available options live. The actual command/output looks much the same across platforms, once the command itself is configured properly.
