### ISSUE TITLE
Page "metadata.rb" typos

### ISSUE THREAD

**Issue by jmcmahon** [chef-boneyard/chef-web-docs-2016#182]
It's not clear from the metadata.rb page whether the attribute for the license should be "licensing" or "license" and if the parameter value is free-form or should be chosen from a list of licensing codes.  

See attached for comments.
![metadata rb chef docs](https://f.cloud.github.com/assets/844169/1307365/0cfc013a-31be-11e3-8716-466d69490470.jpg)

**Comment by jamescott** [comment]
Many thanks for the feedback!

https://github.com/opscode/chef-docs/commit/c5812512dead61e6bd52e03fb26e956a63d31c46

To the license values -- those options (apachev2, gplv2, gplv3, mit, and none) are the options used by the knife subcommand. So I reworded things to hopefully clarify that there are five options and that the values on the Knife side of things aren't the same as the values shown in metadata.rb.

james
