### ISSUE TITLE
azure management certificate info is out-of-date

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#183]
The file `includes_plugin_knife/includes_plugin_knife_azure_certificate.rst` has outdated information with respect to operating the Knife Azure plugin.

It is no longer necessary to use openssl contortions to get the plugin to talk to Azure. Instead, the "publishsettings" file can be used directly by knife azure, either by setting:

``` ruby
knife[:azure_publish_settings_file] = "/path/to/your.publishsettings"
```

or by passing `--azure-publish-settings-file` as a parameter to any `knife azure` command.

**Comment by jamescott** [comment]
The file has been removed from the published topic, though the file itself is still in the source. I do have in the queue to (someday) add the knife config settings for the plugins to the various knife config-related topics.

**Comment by jamescott** [comment]
And updated the description in the plugin doc to mention the path.

https://github.com/opscode/chef-docs/commit/5e3bcaa1e8a4dcd35314b4fe4068b86af2370abb
