### ISSUE TITLE
chef-server.rb settings lacking descriptions

### ISSUE THREAD

**Issue by d-higuchi** [chef-boneyard/chef-web-docs-2016#191]
http://docs.opscode.com/config_rb_chef_server.html

a lot of descriptions has only "Default value" without real descriptions.
so i do not understand and explain what settings mean.

**Comment by jamescott** [comment]
I have been adding these slowly. They are in my queue, but I probably won't get to them until after some new Enterprise Chef features are documented more fully, including Push Jobs, Reporting, and the new Manage Console. That said, a couple of new descriptions were added recently (and I do add them as I run across them). I do want to get all of these finished, with proper descriptions.

**Comment by jamescott** [comment]
Gonna close this as a tracking item. The work to add more descriptions for the various configuration files is ongoing. Many more have been added for Chef 12. I add new ones as I discover them.
