### ISSUE TITLE
handlers documentation doesn't mention start handlers

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#194]
http://docs.opscode.com/essentials_handlers.html

doesn't mention that start handlers are also available.

Actually the chef_handler cookbook needs to be updated to allow them too.

**Comment by jamescott** [comment]
handlers.html is tracking the updated docs. Added some new info, methods, am adding info re: start handlers. Will (eventually, when this topic is finished) set up essentials_handlers and handlers to be identical sets of content (effectively deprecating the essentials_handlers topic).
