### ISSUE TITLE
current index page doesn't link to release notes for older versions

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#216]
The current docs.opscode.com index page doesn't link to release notes for older versions of Chef, only the last major/minor version prior to the current one. If I want to find the release notes for 11.4.x for instance I have to go to the 11.6.x page.

**Comment by jamescott** [comment]
Add this page:

https://docs.chef.io/releases.html

and then it's linked on the main index and also in the top-bar navigation.
