### ISSUE TITLE
document useful helper methods for checking Windows product versions

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#217]
James,

I discovered some interesting helper methods to change recipe behavior based on Windows version.

You can write a recipe with code like this:

``` ruby
require 'chef/win32/version'

win_version = Chef::ReservedNames::Win32::Version.new
```

Now this `win_version` object has useful methods like 

``` ruby
:windows_8_1?
:windows_server_2012_r2?
:windows_8?
:windows_server_2012?
:windows_7?
:windows_server_2008_r2?
:windows_server_2008?
:windows_vista?
:windows_server_2003_r2?
:windows_home_server?
:windows_server_2003?
:windows_xp?
:windows_2000?
```

As well as:

``` ruby
:marketing_name
```

(which returns the product string e.g. “Windows 2012 Server”)

And also:

``` ruby
:cluster?
:core?
:datacenter?
```

For the various types of Windows installation.

Thought that might be useful in the docs somewhere.

**Comment by jamescott** [comment]
OK, candidate #1 for publication: http://docs.opscode.com/dsl_recipe_helper_windows_platform.html

**Comment by juliandunn** [comment]
Thanks James. Looking good overall; a couple of things:
- I found the intro graf a little wordy. Maybe something like this: "The Recipe DSL provides support for determining the specific platform version in a Microsoft Windows environment by using a utility method inside the Chef::ReservedNames::Win32::Version class" ?
- Some code errors in the third code block: Ruby uses "elsif" not "elseif", and also the brackets around each conditional are unnecessary, i.e. `if windows_version.handler_name?` is sufficient)
- `marketing_name` doesn't have a question mark on the end of it, since it just returns a string. (In Ruby, methods that return booleans have a '?' by convention; otherwise they don't.) It also doesn't really mean the Microsoft marketing name, so it won't return "Blue" for Windows 8.1; it'll return "Windows 8.1".
- You can mention that the example installs Powershell 2.0 on systems that don't have it, and it's a publicly-available cookbook at https://ckbk.it/ms_dotnet2 if people want to refer to it.

**Comment by jamescott** [comment]
... and updated!

**Comment by juliandunn** [comment]
Cool, thanks James! Couple last things...
- `marketing_name` doesn't "test for" the marketing name, it just displays it.
- The output on the last line of the document is garbled.

Other than that it's great. :shipit:

**Comment by jamescott** [comment]
All fixed, hooked into main docs, open source, enterprise builds.
