### ISSUE TITLE
recipes aren't tagged, nodes are

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#224]
This page: http://docs.opscode.com/chef/essentials_cookbook_recipes.html

States: "A recipe... May be tagged to facilitate the creation of arbitrary groupings that exist outside of the normal naming conventions an organization may have"

I've never heard of a recipe being tagged. Don't we mean that nodes can be tagged?

**Comment by jamescott** [comment]
I believe you are correct sir!

https://github.com/opscode/chef-docs/commit/659d6754eaa6a3fccba681a4988a05148b43a795
