### ISSUE TITLE
be clearer about "data bag" versus "data bag item"

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#225]
Hey @jamescott,

One point of confusion among a lot of customers is the distinction between "data bag" and "data bag item". We sometimes reinforce this confusion by using the terms interchangeably, when they are not: data bags contain zero or more data bag items.

An example of this confusion is in the section about data bag item encryption: http://docs.opscode.com/chef/essentials_data_bags.html#encrypt-a-data-bag One never actually encrypts a bag as a whole; bag items are individually encrypted, or not. A bag can contain a mix of encrypted and unencrypted items, and in fact, encrypted items within the same bag need not share the same encryption key.

Because we say "data bag" instead of "item", the foregoing facts are not often known by customers and it leads to incorrect perceptions of the utility of encrypted data bags.

Could we do a sweep of the data bag topics and make sure we're precise about whether we're referring to bags or items?

**Comment by jamescott** [comment]
I just did a sweep in the topics that discuss data bag encryption and rewrote stuff to be more clear re: data bag item encryption. The description for the knife `secret` option is going to be in a 2nd checkin.
