### ISSUE TITLE
Ohai 7 is not current

### ISSUE THREAD

**Issue by coderanger** [chef-boneyard/chef-web-docs-2016#235]
"Docs for Current Versions: ... Ohai 7"

Ohai 7 is a pre-release and can't actually be used by normal users. It shouldn't be referred to as the current version and http://docs.opscode.com/ohai.html should not reference it. Any docs for Ohai 7 should have very large warning banners that it is a pre-release.

**Comment by jamescott** [comment]
Good point.

https://github.com/opscode/chef-docs/commit/948f3db8946da38427a2196704ab6b553ce9e288

Is building. Behind a couple of larger builds, but should be updated this evening.

**Comment by coderanger** [comment]
:fireworks: :fireworks: :fireworks:
