### ISSUE TITLE
Docs for depends ~> possibly misleading

### ISSUE THREAD

**Issue by coderanger** [chef-boneyard/chef-web-docs-2016#237]
This operator is more accurately named "pessimistic greater than" and the docs should explain its behavior in more detail as most won't be familiar with the semantics of RubyGems.

**Comment by coderanger** [comment]
This is re: http://docs.opscode.com/essentials_cookbook_metadata.html

**Comment by coderanger** [comment]
Also the docs for conflicts, suggests, replaces, and possibly others should make it clear they are not used currently.

**Comment by jamescott** [comment]
I believe this is the change you're looking for:

https://github.com/opscode/chef-docs/commit/76933cb14016ba3c17f1e034d3d3df3d71cbf906

james
