### ISSUE TITLE
yum packages don't take response_files

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#242]
So far as I know, yum packages don't take `response_file`s:

http://docs.opscode.com/resource_yum.html

I know that this comes from the superclass, but I can't see it in the code for `Chef::Resource::YumPackage`, which confirms my suspicions that it's unused.

**Comment by jamescott** [comment]
Looks like a few others can be removed as well: options, package_name, source, and version.

**Comment by juliandunn** [comment]
@jamescott I think those are still consumed & used by the provider.

**Comment by jamescott** [comment]
Ah, right. The provider. Updated, response_file removed.
