### ISSUE TITLE
Chef Solo doesn't use OpenID anymore

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#243]
Was looking at this:

http://docs.opscode.com/config_rb_solo.html

There are a lot of OpenID-related directives in there that are irrelevant now and should get removed.

**Comment by jamescott** [comment]
Right!

Two changes:

https://github.com/opscode/chef-docs/commit/17fa784169b4ecf5bebfdb0e3b34b2d55e806409

and

https://github.com/opscode/chef-docs/commit/8fb6d53a1443cf7efa547efdf982ad4a5b58e8a3
