### ISSUE TITLE
Windows ACLs missing :read_execute

### ISSUE THREAD

**Issue by troyready** [chef-boneyard/chef-web-docs-2016#257]
The first bullet point of https://github.com/opscode/chef-docs/blob/master/includes_resources/includes_resource_common_windows_security_acl.rst is missing the option `:read_execute` from https://github.com/opscode/chef/blob/master/lib/chef/file_access_control/windows.rb#L206

Its assertion that `:read` grants `GENERIC_EXECUTE` is also incorrect.

**Comment by jamescott** [comment]
I have updated that topic:

https://github.com/opscode/chef-docs/commit/88dc6d554f1cf56286a37d0ef1b673e54700ac23

Thanks for the feedback. Much appreciated.
