### ISSUE TITLE
ohai plugin name attribute semantics changed in Ohai 7

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#259]
http://docs.opscode.com/resource_ohai.html

In Ohai 7, the semantics of the 'plugin' attribute changed to mean the feature provided by the plugin, rather than its name.

Ohai 6 example:

``` ruby
ohai "reload_passwd" do
  plugin "passwd"
end
```

Ohai 7 equivalent:

``` ruby
ohai "reload_passwd" do
  plugin "etc"
end
```

**Comment by jamescott** [comment]
I've updated the ohai resource topic, starting with 11-12 (the first version that includes Ohai 7), and then versioned backwards the previous docs.

https://github.com/opscode/chef-docs/commit/380c84f4b60bae4890a6b25750bbb91fe63dd102
