### ISSUE TITLE
Inconsistency in styling for template resource in execute resource documentation?

### ISSUE THREAD

**Issue by nelsonjchen** [chef-boneyard/chef-web-docs-2016#26]
My question on serverfault:
http://serverfault.com/questions/471911/in-the-chef-resource-document-why-do-they-have-parenthesis-around-the-name-in-t/471930#471930

File in question:
https://github.com/opscode/chef-docs/blob/master/step_resource/step_resource_execute_command_from_template.rst

**Comment by jamescott** [comment]
That is a typo. There are two of them in the execute resource examples, both examples with parentheses are updated to not have parentheses. Thanks for pointing this out.

https://github.com/opscode/chef-docs/commit/7e7564991be6f80167d553d6df400746350319f2

james

**Comment by nelsonjchen** [comment]
Thanks for taking a look!

**Comment by nelsonjchen** [comment]
Hmm, looks like there are more inconsistencies like this throughout the code examples. Like in the package resource.

**Comment by jamescott** [comment]
OK. I will take a cruise through all of those resources examples. Doing that right now.

**Comment by jamescott** [comment]
Resource examples have been updated to reflect not using the parentheses so that the examples are consistent across the various resources. Thanks for pointing out the inconsistency.
