### ISSUE TITLE
remove boilerplate preamble on resource reference pages?

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#262]
So @jamescott I have a pet peeve about the resource reference pages. I hate reading this boilerplate over and over at the top:

> A resource is a key part of a recipe that defines the actions that can be taken against a
> piece of the system. These actions are identified during each chef-client run as the
> resource collection is compiled. Once identified, each resource (in turn) is mapped to a 
> provider, which then configures each piece of the system.

What do you think about getting rid of it across the board?

**Comment by jamescott** [comment]
It's there because most of the resource pages are hit directly from search queries, which means they are the first page people see when they visit the docs site. For many users, it's their first visit, hence the simple boilerplate intro.
