### ISSUE TITLE
Smart quotes are exposed with encoding in this piece of documentation.

### ISSUE THREAD

**Issue by nelsonjchen** [chef-boneyard/chef-web-docs-2016#28]
http://docs.opscode.com/essentials_data_bags_encrypt.html

It's at the last code block.

**Comment by jamescott** [comment]
Awesome. Good catch. You have eagle eyes.

Fixed: https://github.com/opscode/chef-docs/commit/d343e24e12774316635d8939cc098e05f19ffeeb
