### ISSUE TITLE
Docs for the /universe API endpoint

### ISSUE THREAD

**Issue by raskchanky** [chef-boneyard/chef-web-docs-2016#281]
As part of Supermarket, the new community site, there's a new API endpoint called `/universe` that's designed to replace the endpoint by the same name that's currently provided by `api.berkshelf.com`.  The PR for said endpoint can be seen here:

https://github.com/opscode/supermarket/pull/431

As part of the work for implementing this endpoint, I'd like to write some docs for it, but I'm not sure where those docs would go in this repo.

Can you point me to the right place?  Thanks!

**Comment by jamescott** [comment]
This folder:

https://github.com/opscode/chef-docs/tree/master/includes_api_cookbooks_site

There are two new files that have _universe in them. The root topic and then one for a GET endpoint. If there are other endpoints, use GET as a template and just name them by what they are called (_post, _put, and so on).

When you're ready to add them to a live page, please do a PR agains this topic:

https://github.com/opscode/chef-docs/blob/master/chef_master/source/api_cookbooks_site.rst

Those endpoints are alphabetized, so at the end. Same header types, path patterns, and so on.

**Comment by jamescott** [comment]
https://docs.chef.io/api_cookbooks_site.html#universe
