### ISSUE TITLE
`chef gem` installs gems in ~/.chefdk

### ISSUE THREAD

**Issue by jtimberman** [chef-boneyard/chef-web-docs-2016#286]
I think it should be noted in the `chef gem` documentation that gems installed with the command will be installed under `~/.chefdk` - as documented in the [chef-dk README](https://github.com/opscode/chef-dk#chef-gem).

**Comment by jamescott** [comment]
Expanded intro w/install path:

https://github.com/opscode/chef-docs/commit/dc9932aa2aefaf9a729bf6819523b4dd2e01ae97
