### ISSUE TITLE
More information about `chef gem`

### ISSUE THREAD

**Issue by jtimberman** [chef-boneyard/chef-web-docs-2016#287]
The `chef gem` documentation should include examples and more information. It's a wrapper around using the normal rubygems `gem` command that users may be familiar with, but installs and uses gems from a chefdk specific location.
## Examples

Show an existing gem in the Chef DK:

```
% chef gem list chef-dk

*** LOCAL GEMS ***

chef-dk (0.1.0)
```

Install a new gem and see its contents:

```
% chef gem install knife-config
Successfully installed knife-config-1.1.0
1 gem installed

% chef gem content knife-config
/Users/jtimberman/.chefdk/gem/ruby/2.1.0/gems/knife-config-1.1.0/LICENSE
/Users/jtimberman/.chefdk/gem/ruby/2.1.0/gems/knife-config-1.1.0/README.md
/Users/jtimberman/.chefdk/gem/ruby/2.1.0/gems/knife-config-1.1.0/lib/chef/knife/config.rb
/Users/jtimberman/.chefdk/gem/ruby/2.1.0/gems/knife-config-1.1.0/lib/knife-config.rb
```

**Comment by jamescott** [comment]
Added examples, updated description:

https://github.com/opscode/chef-docs/commit/d7af21c25054371866d9aea84784665b49398f2b
