### ISSUE TITLE
windows_shortcut is poorly documented

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#291]
Migrated from JIRA COOK-4563 as part of the cleanup of public JIRA.

Quoting here:

---

The documentation[1] for the windows_shortcut resource is poorly documented. It is missing examples. The descriptions of the attributes is poor and unhelpful.

The resource name is mapped to the name attribute.

cwd is the directory to start in
name is the full path of the shortcut e.g. "C:\tmp\path
program.lnk"
target is the path to the program to execute. e.g. "C:\path\to
program.exe"

references:
https://tickets.opscode.com/browse/COOK-667
https://github.com/opscode/cookbooks/pull/349/files

[1] http://docs.opscode.com/lwrp_windows.html#windows-shortcut

**Comment by Tech356** [comment]
With the removal of the documentation at `http://docs.opscode.com/lwrp_windows.html#windows-shortcut`, windows_shortcut is not documented at all. The page points to `https://github.com/opscode-cookbooks/windows` but the `readme.md` does not mention `windows_shortcut`.

**Comment by jamescott** [comment]
This issue should be made against this repo: https://github.com/opscode-cookbooks/windows

At least until the windows_shortcut resource is moved into core Chef.
