### ISSUE TITLE
Chef Analytics install link goes to a redirected page

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#297]
On the main page of [docs.opscode.com](http://docs.opscode.com/#chef-analytics), if you click "Install Chef Actions" it goes to a page that is now redirected to something else.

Also, are we calling this "Analytics" or "Actions"?

**Comment by jamescott** [comment]
This is the correct page:

https://github.com/opscode/chef-docs/commit/bf66e504a863b133b16d733bb8507171765ba6a8
