### ISSUE TITLE
registry_key :create -- Should mention it updates as well

### ISSUE THREAD

**Issue by docwhat** [chef-boneyard/chef-web-docs-2016#307]
The text for `action :create` for `registry_key` currently says:

> Default. Use to create a registry key.

It should say something like:

> Default. Use to create a registry key and update the value if it doesn't match.

This actually seems to be systematically wrong in the docs.

e.g. `template`, `file` and  `cookbook_file` all same the same thing and should also mention it ensures the file is updated as well.

I would have submitted a pull request, but I couldn't figure out where the text came from (I'm unfamiliar with `.rst` files).

Ciao!

**Comment by docwhat** [comment]
URL: http://docs.opscode.com/resource_registry_key.html#actions

**Comment by jamescott** [comment]
Yep. On it. Will be a few minutes here while I figure out the changes. And then push for a new build.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/842e4840b182a6193e24afde04b06690b43e1e2a

This will take a little while for the build to crawl through all the builds and replace the strings, but sometime later this afternoon for the current docs. I'll have to reset the makefile to pick this change up in older doc version builds when they get rebuilt.

**Comment by docwhat** [comment]
Aha! `swaps` -- I did not know that. Thanks, @jamescott.

**Comment by adamedx** [comment]
The "create and update" suggested change is the correct one to take @jamescott. Thank you @docwhat.
