### ISSUE TITLE
Registry_key does not specify how to set the default value of a key

### ISSUE THREAD

**Issue by Tech356** [chef-boneyard/chef-web-docs-2016#311]
Each key in the registry contains a `(Default)` value of type string. The documentation does not state how to set this value using the registry_key resource. Through trial and error I have found that an empty string name sets the default value.

```
registry_key "Set default value" do
    action :create
    key "HKLM\\Software\\Test\\Key\\Path"
    values [
        {:name => '', :type => :string, :data => 'test'},
    ]
end
```

The documentation should contain a small blurb and example for how to set the default key.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/b3a0b9bf01015c8ee9d7545f07dbc6fefdd50537

Thanks!
