### ISSUE TITLE
X-Ops-Sign clarification.

### ISSUE THREAD

**Issue by thorduri** [chef-boneyard/chef-web-docs-2016#312]
The [documentation](http://docs.opscode.com/api_chef_server.html) for `X-Ops-Sign` says to set the value to `version=1` however the example a little further down has it as `X-Ops-Sign: algorithm=sha1;version=1.0;`

Using either format works as expected, but it seems prudent to set the algorithm I think.

**Comment by jamescott** [comment]
This got sync'd up a while back and should be good to go:

https://docs.chef.io/api_chef_server.html

Thank you for the feedback and apologies for the belated follow-up in the issue itself!

james
