### ISSUE TITLE
require docs are incorrect

### ISSUE THREAD

**Issue by coderanger** [chef-boneyard/chef-web-docs-2016#313]
Pending a full rewrite, http://docs.opscode.com/lwrp_custom_provider_ruby.html#require should be removed ASAP as it is entirely incorrect.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/68c2729c69f90bbf239a8667ea3e58ee7240b875

**Comment by coderanger** [comment]
Thanky!
