### ISSUE TITLE
Confusing text in json_file Handler and error_report Handler sections

### ISSUE THREAD

**Issue by christinedraper** [chef-boneyard/chef-web-docs-2016#331]
I've been trying to understand handlers from the "About Handlers" section. One of the things that confused me is in the sections on the json_file Handler and error_report Handler. I misread these sections to say that these handlers need to be enabled by adding Ruby code to the client.rb, AND by adding a chef_handler in the recipe.  From what I've found, they are alternatives - it would be useful to make that clear.

**Comment by jamescott** [comment]
You are correct -- here's the update:

https://github.com/opscode/chef-docs/commit/5d48f3436ff4d513a4f2b6667a962a2fdac68ab4

Thanks for the feedback! Hopefully this change makes the behavior more clear.
