### ISSUE TITLE
Error_report Handler section has incorrect 

### ISSUE THREAD

**Issue by christinedraper** [chef-boneyard/chef-web-docs-2016#332]
The error_handler in chef 11.12.8 does not take any arguments. The documentation

http://docs.getchef.com/handlers.html#error-report-handler

currently shows arguments... it should instead have:

```
require 'chef/handler/error_report'
report_handlers << Chef::Handler::ErrorReport.new()
exception_handlers << Chef::Handler::ErrorReport.new()
```

and

```
chef_handler "Chef::Handler::ErrorReport" do
  source "chef/handler/error_report"
  action :enable
end
```

**Comment by jamescott** [comment]
Arguments should be valid:

https://github.com/opscode-cookbooks/chef_handler/blob/master/resources/default.rb#L25

**Comment by christinedraper** [comment]
Apologies, I wasn't clear on the issue. Although it is valid to specify arguments, the error_report handler does not do anything with the :path argument. It always saves the data in the file cache: 

https://github.com/opscode/chef/blob/master/lib/chef/handler/error_report.rb#L27

So it is misleading to have (:path => "/var/chef/reports")... people will think it should change the path (like it does in the JSON handler).

**Comment by jamescott** [comment]
Ah, gotcha. Here's the fix:

https://github.com/opscode/chef-docs/commit/21e2005221cb0b47f2235690b150425921918be5

Thanks for following up!

james
