### ISSUE TITLE
supports :both=>true is not valid attribute value for chef_handler

### ISSUE THREAD

**Issue by christinedraper** [chef-boneyard/chef-web-docs-2016#333]
http://docs.getchef.com/lwrp_chef_handler.html states that the supports attribute has possible values:

Possible values: :exception, :report, :both (exception and report handlers), or :start. Default value: { :report => true, :exception => true }.

As far as I can tell, :both is not a valid value. It causes an exception.

**Comment by jamescott** [comment]
Good catch!
https://github.com/opscode/chef-docs/commit/228d824ccee6c6c29a3296d89dca074e99aba4e6
