### ISSUE TITLE
Default port is wrong for knife serve

### ISSUE THREAD

**Issue by christinedraper** [chef-boneyard/chef-web-docs-2016#336]
The docs for knife serve say the default port is 8900 (in two places in the doc)

https://docs.getchef.com/knife_serve.html

I just tried it, and it defaulted to the normal chef-zero default port of 8889

**Comment by jamescott** [comment]
I have updated the docs based on this:
https://github.com/opscode/chef/blob/master/lib/chef/config.rb#L302

commit:
https://github.com/opscode/chef-docs/commit/798b262f24dc82fec49452a3ce85f9baa8fca1f6
