### ISSUE TITLE
missing attributes for `machine` resource

### ISSUE THREAD

**Issue by jtimberman** [chef-boneyard/chef-web-docs-2016#337]
This page:

http://docs.getchef.com/resource_machine.html

is missing documentation about the following allowed attributes to the machine resource:
- tag
- attribute
- recipe
- role

tag, attribute, and recipe are all used in the examples. role isn't, but it works too, specifying a chef role.

**Comment by PierreRambaud** [comment]
Seems to be fixed: https://github.com/opscode/chef-docs/blob/master/includes_resources/includes_resource_machine_attributes.rst

**Comment by jtimberman** [comment]
Yay!
