### ISSUE TITLE
Cookbook_file resource name attribute

### ISSUE THREAD

**Issue by Tech356** [chef-boneyard/chef-web-docs-2016#338]
In the Syntax section, the `name` attribute is said to map to `path`.

```
'name' is the name of the resource block; when the 'path' attribute is not specified as
part of a recipe, 'name' is also the path to the file
```

but the `source` attribute says that the `name` maps to `source`:

```
Default value: the 'name' of the resource block (see Syntax section above).
```

**Comment by jamescott** [comment]
Good catch!

https://github.com/opscode/chef-docs/commit/23bbddbc1963884790a8245a85f6557ed95e309e

Thanks!
