### ISSUE TITLE
chef-server-ctl association/dissociation commands are incorrect

### ISSUE THREAD

**Issue by jtimberman** [chef-boneyard/chef-web-docs-2016#340]
The [docs mention](http://docs.getchef.com/ctl_chef_server.html#user-associate) `user-associate` and `user-dissassociate`. The correct commands are `org-associate` and `org-dissociate`.

```
ubuntu@ubuntu-chef12:~$ sudo chef-server-ctl user-associate
I don't know that command.
```

```
ubuntu@ubuntu-chef12:~$ sudo chef-server-ctl help
...snip
org-associate
  Associate a user with an organization.
org-dissociate
  Dissociate a user with an organization.
```

**Comment by jamescott** [comment]
Thanks. Here's the commit:

https://github.com/opscode/chef-docs/commit/49ab7989908d48d1b91c60d1a22020f92cc624e4

**Comment by jtimberman** [comment]
:heart:
