### ISSUE TITLE
cron resource example indicates that it accepts a symbol and it doesn't

### ISSUE THREAD

**Issue by miketheman** [chef-boneyard/chef-web-docs-2016#343]
http://docs.getchef.com/chef/resources.html#cron

> The day of the week on this entry should run (0 - 6), where Sunday = 0. Default value: *. May be entered as a symbol, e.g. :monday or :friday.

```
Option weekday must be a kind of [Integer, String]!  You passed :monday.
```

**Comment by jamescott** [comment]
which version of the chef-client are you running?

**Comment by jamescott** [comment]
This is functionality added in chef-client 11.12. I updated the "What's new" for the release notes:
http://docs.getchef.com/release/11-12/release_notes.html#what-s-new

https://github.com/opscode/chef-docs/commit/3ed520a4ba32ab3ae76e6bd679cc122288588e54

**Comment by miketheman** [comment]
```
$ chef-client -v
Chef: 11.12.8
```

**Comment by miketheman** [comment]
You may also want to look at using Sphinx's markup to denote when a thing was introduced.

http://sphinx-doc.org/markup/para.html#directive-versionadded

**Comment by jamescott** [comment]
Can you file a bug against the chef-client re: the issue you are having with the weekday attribute? It's supposed to accept the symbols, starting with 11.12.
