### ISSUE TITLE
Document busser versions for Test Kitchen's .kitchen.yml 

### ISSUE THREAD

**Issue by jtimberman** [chef-boneyard/chef-web-docs-2016#352]
[This issue](https://github.com/test-kitchen/test-kitchen/issues/515) raises a query about getting specific versions of Test Kitchen's "bussers" by specifying them in the `.kitchen.yml`, and by special directory structures in the `test` directory.

Since we maintain documentation about Test Kitchen as part of the ChefDK, I think we should add information about this, as I'm not aware of this kind of documentation existing elsewhere at this time.

**Comment by jamescott** [comment]
Here's a drafty version of a section that discusses Busser settings in a Kitchen.yml file:

https://github.com/opscode/chef-docs/blob/master/includes_test_kitchen/includes_test_kitchen_yml_example_busser.rst

**Comment by joventuraz** [comment]
Hello, test-kitchen/test-kitchen#518 adds the functionality for the plugins array in the .kitchen.yml file.

**Comment by jamescott** [comment]
Updated the busser section in the kitchen.yml config docs to reflect this PR.

https://github.com/opscode/chef-docs/commit/9f10ca338d8d4cea3235489d23df7db049bd78e6
