### ISSUE TITLE
disk space for chef client

### ISSUE THREAD

**Issue by obazoud** [chef-boneyard/chef-web-docs-2016#360]
there's nothing about expected disk space on the requirements for chef client.

**Comment by jamescott** [comment]
docs commit: https://github.com/opscode/chef-docs/commit/f2afcefe9ad87dde75790128ceddfbfcbd8f9551

will be on this page sometime today:

http://docs.getchef.com/chef_system_requirements.html#chef-client

**Comment by obazoud** [comment]
Thanks!
