### ISSUE TITLE
"knife ec2 server list" doesn't take all the options listed

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#364]
https://docs.getchef.com/plugin_knife_ec2.html#id7

Only takes the following options that are specific to AWS:

```
    -A, --aws-access-key-id KEY      Your AWS Access Key ID
        --aws-credential-file FILE   File containing AWS credentials as used by aws cmdline tools
    -K SECRET,                       Your AWS API Secret Access Key
        --aws-secret-access-key
        --availability-zone          Show availability zones
        --region REGION              Your AWS region
```

It also takes all the other generic knife options, of course.

**Comment by jamescott** [comment]
This is the list I have with base options + server list-specific options:

https://github.com/opscode/chef-docs/blob/0beb678a6be5aa46c73a73412cf0f71d1048f656/includes_plugin_knife/includes_plugin_knife_ec2_server_list_options.rst
