### ISSUE TITLE
"knife ec2" page has incorrect settings for IAM profile

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#365]
The option for choosing the IAM profile during `knife ec2 server create` is actually:

```
        --iam-profile NAME           The IAM instance profile to apply to this instance.
```

It is currently incorrectly documented as `--use-iam-profile` which isn't a valid option.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/0a40c4020b9caac58d0462b8bffde350d2f84d21

**Comment by jamescott** [comment]
undoing this, hold on...

**Comment by jamescott** [comment]
sync all the subcommands, options: https://github.com/opscode/chef-docs/commit/0beb678a6be5aa46c73a73412cf0f71d1048f656
