### ISSUE TITLE
Small typo with org-disassociate

### ISSUE THREAD

**Issue by tiago-cruz-movile** [chef-boneyard/chef-web-docs-2016#370]
Page: https://docs.getchef.com/server_orgs.html

Command: org-disassociate
- Wrong:

```
[root@chef12-server2 ~]# chef-server-ctl | grep org-disassociate
```
- Correct:

```
[root@chef12-server2 ~]# chef-server-ctl | grep org-dissociate
  org-dissociate
```

Version: chef-server-core-12.0.0_rc.5-1.el5.x86_64.rpm

**Comment by jamescott** [comment]
We may change the name of the commands to something shorter. I will wait on that change before updating.

**Comment by jamescott** [comment]
These commands have been updated to:

http://docs.getchef.com/ctl_chef_server.html#org-user-add
http://docs.getchef.com/ctl_chef_server.html#org-user-remove

and will be part of the upcoming Chef Server 12 final release.
