### ISSUE TITLE
12.0 release notes have error about AIX service providers

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#371]
Hey @jamescott -- there are actually two separate providers that are new for Chef 12 on AIX:
- `Chef::Provider::Service::Aix` -- which is the default, and which manages Subsystem Resource Controller (SRC) services. This is the provider selected by default (if users simply write a "service" resource)
- `Chef::Provider::Service::AixInit` -- to manage any BSD-init-based services

The release notes [here](http://docs.getchef.com/release/12-0/release_notes.html#ibm-aix-platform-support) only mention the Aixinit provider at present.

**Comment by jamescott** [comment]
Will the chef-client pick the AixInit provider when it detects the BSD-init based services automatically? Or does the long-name provider need to be specified?

**Comment by jamescott** [comment]
Also, added the provider: https://github.com/opscode/chef-docs/commit/aeb494692196945b00344639df898227c45418da

**Comment by juliandunn** [comment]
The long name needs to be specified as Chef can only have one default provider per platform and that is the SRC provider on AIX.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/ab09d2075f77d12cf3c0e781e9c7da6558f88852
