### ISSUE TITLE
bff_package example

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#381]
@jamescott ,

Here's an example of how to use `bff_package`.

Because `bff_package` is the default package provider on AIX, users can call it directly using `package`. Here is a worked example of installing part of the IBM XL C/C++ compiler using the resource:

``` ruby
package "xlccmp.13.1.0" do
  source "/var/tmp/IBM_XL_C_13.1.0/usr/sys/inst.images/xlccmp.13.1.0"
  action :install
end
```

Note that BFFs don't always end in the extension `.bff` -- that's legit. The provider will do its work either way.

`source` is always a required attribute. Unlike other package providers, it must be a local filesystem location, because `installp` doesn't understand how to retrieve files off HTTP/FTP servers.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/6eef3ba6c720b162656e1efca28ddb2977e4bd15

**Comment by juliandunn** [comment]
Cool, can you replace the "Examples: None" section on the [release notes](http://docs.getchef.com/release/12-0/release_notes.html) with it?

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/2021d610138389afedcf80370a800e504e3d8147
