### ISSUE TITLE
Windows Event Logger text is confusing

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#384]
Chef Client 12 release notes have this blurb:

``` text
Events are sent to the Application event log on the Windows platform by default
The disable_event_logger settings in the client.rb file is set to true by default.
This sends events for the start and end of a chef-client run, plus an event if the chef-client run fails,
to the Microsoft Windows “Application” event log.
```

This text makes no sense. If the default is to send events to the Windows application log, isn't the default for `disable_event_logger` actually `false` ? Also, why mention the setting at all if the behavior is `false`? Or only mention it in the context of "If you wish to disable this functionality, set this setting to `true`

/cc @jdmundrawala

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/1350a346f1bb975069cb23c73c9737df1d2e57ba

and

https://github.com/opscode/chef-docs/commit/1be209cf00e046329a23ed192a98faf8142f8308
