### ISSUE TITLE
make a static page for the old Approved Contributors from the Wiki

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#388]
We've [announced](http://lists.opscode.com/sympa/arc/chef/2014-11/msg00107.html) that we'd like to decommission the old Opscode Wiki at the end of the year. You'll likely see tickets from me or others about migrating any bits of remaining relevant content somewhere.

One such page is the old, pre-Supermarket "signed CLA" page. Since this is no longer changing, perhaps we can export it and move it to docs? Docs isn't the perfect fit, but it's also the most expedient.

http://wiki.opscode.com/display/chef/Approved+Contributors

**Comment by jamescott** [comment]
What about a MD file in the chef repo on github?

Also, that's one impressive table. So LOL MD tables.

**Comment by juliandunn** [comment]
I guess that would work. @danielsdeleo raised this to me, and said he was agnostic about the solution, so maybe he'd be ok with that?

**Comment by jamescott** [comment]
CONTRIBUTING_APPROVED.MD

**Comment by lamont-granquist** [comment]
only possible concern there is people who think the way to get on the CLA list is to issue PRs against that file (particularly if it starts to get indexed by google and pops up high in search rankings).  needs a nice bigass unmistakable banner on the top that its a historical file and a pointer to signing CLAs in supermarket.  we probably need that on the file anyway, though.

**Comment by lamont-granquist** [comment]
I'd also suggest DEPRECATED_CONTRIBUTORS_LIST.md or something, although it might sound like the contributors themselves are deprecated....

**Comment by danielsdeleo** [comment]
CLA_ARCHIVE.md ?

**Comment by lamont-granquist** [comment]
Yep something like that sounds good to me.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/blob/master/CLA_ARCHIVE.MD

Feel free to move that into the chef repo whenev's.
