### ISSUE TITLE
Invalid ePUB

### ISSUE THREAD

**Issue by fox91** [chef-boneyard/chef-web-docs-2016#395]
ePUB generated by `make epub` is invalid.
I checked with [epubcheck](https://github.com/IDPF/epubcheck) with
`java -jar epubcheck.jar /tmp/chef-docs/build/epub-master/ChefDocs.epub`
This is the output: https://gist.github.com/cffbe90f39d2876fa7c0

**Comment by jamescott** [comment]
That's not too surprising. chef-docs is optimized for the HTML output and that is the only (supported) location the content is published is the docs website.

You might try building the chef_master directory by itself locally without using the make epub command. An epub-specific build may need to have its own build directory with dedicated structures to keep the format happy.
