### ISSUE TITLE
Broken Link Pointing to 'docs.gethef.com'

### ISSUE THREAD

**Issue by skidder** [chef-boneyard/chef-web-docs-2016#396]
There's a broken link on the following Chef Docs page:
https://docs.getchef.com/resource_container_service.html

"This topic has been moved to http://docs.gethef.com/containers.html."

The hostname is 'docs.gethef.com' but should be 'docs.getchef.com'.

**Comment by skidder** [comment]
A quick search in the repository for 'gethef' shows a total of 7 files affected.

**Comment by jamescott** [comment]
Thank you! That's quite the typo.

https://github.com/opscode/chef-docs/commit/66895f5db9046df71c268e1eafca64c3b1f923f3

There are actually just two instances. I'll rebuild that /translate directory and that'll pick up all the latest strings for the entire doc set. And will fix this specific issue as well.
