### ISSUE TITLE
deploy_branch is not a thing

### ISSUE THREAD

**Issue by coderanger** [chef-boneyard/chef-web-docs-2016#397]
re: https://docs.getchef.com/resource_deploy.html#deploy-branch

That isn't a thing that has ever existed that I can tell, guessing just a miscommunication.

**Comment by jamescott** [comment]
It's a thing that exists: 

https://github.com/opscode/chef/blob/master/lib/chef/resource/deploy_revision.rb#L34-L42

That said, using deploy_revision is preferred over deploy_branch. This commit fixes the typo too :)

https://github.com/opscode/chef-docs/commit/b74c5cfa9f756a3bde515ba001c0152b5ddda9f4

**Comment by coderanger** [comment]
Should probably make it clear that it isn't just used in the same way, it is just an alias for the same thing.

**Comment by jamescott** [comment]
Sure! How's this?

https://github.com/opscode/chef-docs/commit/cbad0eea5da6a5636d64ebc62a860cd2be15e97f

**Comment by kwilczynski** [comment]
Paging @coderanger. Is the change better? /cc @jamescott
