### ISSUE TITLE
chef-sync.rb's install_path has broken brackets.

### ISSUE THREAD

**Issue by d-higuchi** [chef-boneyard/chef-web-docs-2016#398]
in http://docs.getchef.com/server/server_replication.html#settings

```
install_path']  Default value: "/opt/chef-sync".
```

includes_config/includes_config_rb_sync_settings.rst:

```
   * - ``install_path']``
     - Default value: ``"/opt/chef-sync"``.
```

**Comment by kwilczynski** [comment]
Fixed by #399.

**Comment by kwilczynski** [comment]
@cl-lab-k nice catch! A very keen eye :+1:

**Comment by jamescott** [comment]
@cl-lab-k Agreed. Thank you!

@kwilczynski In the configuration files, the settings are always listed alphabetically.

https://github.com/opscode/chef-docs/commit/f713980f2ccbfbb5e6a671f152e79b9ffabd40c5
