### ISSUE TITLE
Shouldn't .chef be added to .gitignore?

### ISSUE THREAD

**Issue by jblaine** [chef-boneyard/chef-web-docs-2016#40]
No mention of it here: http://docs.opscode.com/install_workstation.html

**Comment by jamescott** [comment]
Yes. Added. The staging URL to see the change: http://chef-docs.s3-website-us-east-1.amazonaws.com/install_workstation.html

**Comment by jblaine** [comment]
Small typo:

```
Add .chef to the .gitignore file to prevent uploading the contents of the /.chef folder to github
```

should be

```
Add .chef to the .gitignore file to prevent uploading the contents of the .chef folder to github
```

**Comment by sethvargo** [comment]
Related: http://tickets.opscode.com/browse/CHEF-3942

**Comment by jamescott** [comment]
@jblaine Fixed that directory name. Thanks!
