### ISSUE TITLE
Analytics 1.1 Standalone needs  oc-id configuration

### ISSUE THREAD

**Issue by jamesc** [chef-boneyard/chef-web-docs-2016#402]
The standalone 1.1 instructions need the same Step 2. as for the tiered instructions:
![image](https://cloud.githubusercontent.com/assets/276490/5101336/7a8eb710-6f6b-11e4-8d80-11510eeade09.png)

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/e0def79c3792e430f935f50352aa61005763683f
