### ISSUE TITLE
windows_package shows incorrect symbols vs strings

### ISSUE THREAD

**Issue by miketheman** [chef-boneyard/chef-web-docs-2016#403]
> Attribute Description
> installer_type  The package type. Possible values: :inno, :installshield, :msi, :nsis, and :wise.

``` console
Chef::Exceptions::ValidationFailed: Option installer_type must be a kind of [String]!  You passed :msi.
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/mixin/params_validate.rb:157:in `_pv_kind_of'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/mixin/params_validate.rb:70:in `block (2 levels) in validate'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/mixin/params_validate.rb:67:in `each'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/mixin/params_validate.rb:67:in `block in validate'
        from C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-
```

**Comment by jamescott** [comment]
https://github.com/opscode/chef/commit/c3dfc8ad3007ebd9628e2a0da87b5019f103ffbb#diff-3c9b1a519cef717fb2fa5d2f52a30477

It's **supposed** to be a symbol. That said, engineering is verifying this. If you use the windows cookbook, things **should** behave normally in the meantime.

**Comment by miketheman** [comment]
Don't wanna use the windows cookbook - want to use the Chef primitives. :)

**Comment by jamescott** [comment]
Yeah!

Engineering just confirmed that the string is correct for 11.x versions and will become symbol for 12.0. I am going to make the docs updates right now, and put a note in the 11.x version about that change.

Incidentally, the 12.0 client will move a couple more resources from the windows cookbook into core Chef -- reboot and windows_service: 

http://docs.getchef.com/release/12-0/release_notes.html

**Comment by jamescott** [comment]
This:

https://github.com/opscode/chef-docs/commit/6a637d4c63e447aa7b1671c391b7fac25e4bdd65

will be a few hours, but should be live on the pages by late afternoon. Thank you for sending this in!

james

**Comment by miketheman** [comment]
No problem!
