### ISSUE TITLE
Add Chef Server REST API Example

### ISSUE THREAD

**Issue by dsklopp** [chef-boneyard/chef-web-docs-2016#404]
At https://docs.getchef.com/api_chef_server.html it would be helpful if a functional example is given to query the Chef Server API.  Below is code I wrote and tested to do just this.  It only queries the Chef server for a listing of organizations and a listing of users.

```
# This script is meant to be run from a directory containing the proper .chef
# for the pivotal user
require 'chef'

Chef::Config.from_file(".chef/pivotal.rb")
rest = Chef::REST.new(Chef::Config[:chef_server_url])
orgs = rest.get_rest("/organizations")

puts "\n=== Listing of organizations"
orgs.each do |org|
  puts org
end

puts "\n=== Listing of Users"
users = rest.get_rest("/users")
users.each do |user|
  puts user
end
```

A sample .chef/pivotal.rb file is given below (note the prereqs of a proper pivotal.pem and it's sample location).  IP Addresses will need to be updated.

```
current_dir = File.dirname(__FILE__)
node_name "pivotal"
chef_server_url "https://192.168.1.2:443"
chef_server_root "https://192.168.1.2:443"
client_key "#{current_dir}/pivotal.pem"
```

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/5611e70c9444026aa95089088d8e9c4f218ec00a

Is on the page: https://docs.getchef.com/api_chef_server.html#query-for-users-and-orgs

I just submitted an update to correctly format that 2nd code block. 

Thank you for sending this in.
