### ISSUE TITLE
Search with Environment example incorrect

### ISSUE THREAD

**Issue by gwaldo** [chef-boneyard/chef-web-docs-2016#408]
On the [resource_template documentation page](https://docs.getchef.com/resource_template.html), the example for including the chef environment as a condition is incorrect.  Instead, should be `AND chef_environment:#{node.chef_environment}")`

Fixed in https://github.com/opscode/chef-docs/pull/407

**Comment by kwilczynski** [comment]
@gwaldo Thank you! Merged.
