### ISSUE TITLE
Where to get knife.rb and PEM stuff for OSS Chef Server?

### ISSUE THREAD

**Issue by jblaine** [chef-boneyard/chef-web-docs-2016#41]
Workstation install step (http://docs.opscode.com/install_workstation.html)

```
Download .pem files and knife.rb

[ This step is not required for the open source Chef Server ]
...
```

Where are they for the open source Chef Server? Where does one get them? Login to the web UI and generate a new private key for the 'chef-validator' client? Needs docs.

**Comment by jamescott** [comment]
Thanks Jeff. Updated for both open source and Hosted/Private scenarios.

Staging URL: http://chef-docs.s3-website-us-east-1.amazonaws.com/install_workstation.html

**Comment by jblaine** [comment]
James,

I took a look.

```
chef-validator.pem. This private key is created by the open source Chef Server on
startup and is located in the /etc/chef folder on the server after it is created.
```

The directory for _Chef 11_ Server's copy of the `chef-validator` private key file is `/etc/chef-server`, not `/etc/chef`

Also, you might want to consider linking to http://docs.opscode.com/config_rb_knife.html in this overall section.

Playing devil's advocate:

```
The validation_key attribute in the knife.rb must contain the validation key.
```

Not very clear or helpful.

"...must specify the full _filesystem path_ of the validation private key."

**Comment by jblaine** [comment]
Oh, and thank you :)

**Comment by jamescott** [comment]
Ah. Fixed that tautology. Should be live on the full docs site now.
