### ISSUE TITLE
add example for lazy template variables evaluation

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#410]
We currently have [examples for lazy attribute evaluation](https://docs.getchef.com/resource_common.html#lazy-attribute-evaluation) but the syntax can be quite tricky when trying to do this with template variables. After some trial-and-error I discovered that this works best:

``` ruby
template '/tmp/foozolix.txt' do
  source 'foozolix.txt.erb'
  variables(
    lazy {
      {:foozolix => node.run_state['some_junk']}
    }
  )
end
```

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/21913995824e8dd07f510cc0d438ad898b066b1c

**Comment by juliandunn** [comment]
Your references are very obscure, James, but :+1:

**Comment by erkolson** [comment]
Perhaps expand this further?  I banged my head on this a little while today trying to figure out how to get more than one thing in the lazy block.  Maybe it is obvious to others more fluent in ruby but I did not understand why {{}} was necessary...

``` ruby
template '/tmp/foozolix.txt' do
  source 'foozolix.txt.erb'
  variables(
    lazy {
      {
         :foozolix => node.run_state['some_junk'],
         :toast_uid => node['etc']['passwd']['toast']['uid']
      } 
   }
  )
end
```

**Comment by jamescott** [comment]
@erkolson Am updating the example with your changes right now.

**Comment by eugeneromero** [comment]
Something else that could be mentioned in the docs: How to handle a situation with several attributes, but where only one of them needs to be evaluated lazily. Do all of them need to be added to the lazy block? Is there a way of listing some of them normally, and one lazily? For example (this does NOT work):

```
variables(
    mail_from: node['var'],
    mail_host: node['foo'],    
    lazy {
        {
            secret_key: node['key']
        }
    }
)
```

So, what is the correct form / best practice?

**Comment by sekrett** [comment]
@erkolson , first {} is block, second {} is the hash.

@jamescott I think you need an example with at least two variables. For me it's obvious you need one lazy block for all vars regardless it needs to be lazy or not, but some people are confused.

**Comment by marcomancuso** [comment]
@papa-gene I know it's almost 1 year late now but I believe it should be possible to do:
```
variables(
    mail_from: node['var'],
    mail_host: node['foo'],    
    secret_key: lazy { node['key'] }
)
```

**Comment by eugeneromero** [comment]
@marcomancuso this is still valuable information though, thanks!

**Comment by davidalpert** [comment]
this isn't working for me. using this syntax:
```
variables(
    one_thing: 'a',
    another_thing: 'b',
    secret_key: lazy { lookup_the_secret_key() }
)
```
and the following `.erb`:
```
[secret_key]
<%= @secret_key %>
```
I'm getting the following output rendered on converge:
```
[secret_key]
#<Chef::DelayedEvaluator:0x000000079dbeb0@C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/my-cookbook/recipes/my-recipe.rb:35>
```

**Comment by davidalpert** [comment]
this seems to work:
```
variables lazy {
  {
      one_thing: 'a',
      another_thing: 'b',
      secret_key: lookup_the_secret_key()
}
```
with the following `.erb`:
```
[secret_key]
<%= @secret_key %>
```
got me the following output rendered on converge:
```
[secret_key]
secret_key_value
```

It seems that the trick was:
1. to place the `lazy { }` around the _entire_ variables hash rather than just one value; and
2. remember that the `lazy { }` block needed to return a hash, so that required two sets of brackets like this:
```
variables lazy {
  {
     key: value,
     key2: value2,
     key3, lazyvalue3
}
```

**Comment by spuder** [comment]
rubocop / cookstyle prefers syntax

```ruby
variables(
  lazy do
    {
      :foo => 'bar'
    }
  end
)
```
