### ISSUE TITLE
bootstrap --distro is deprecated, bootstrap page should be updated for --bootstrap-template

### ISSUE THREAD

**Issue by mattray** [chef-boneyard/chef-web-docs-2016#414]
According to the Chef 12 release notes, --distro and --template-file are deprecated.
http://docs.getchef.com/release/12-0/release_notes.html
The page for bootstrap features both prominently.
https://docs.chef.io/knife_bootstrap.html
It probably needs to be updated to feature --bootstrap-template

**Comment by jamescott** [comment]
Updated. Knife bootstrap page no longer mentions --distro and the --bootstrap-template is the long name for -t and the examples in the page are updated and the previous docs versions are versioned.
