### ISSUE TITLE
document the need to set system limits on AIX

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#420]
Over in https://github.com/opscode/chef/issues/2531 we discovered that AIX LPARs need to have their system process limits increased in order to run Chef Client; the out-of-the-box limits from IBM are too low. This information needs to be added to the client 12.x release notes.

Users will know if the system limits are too low if Chef can't create any threads. See the aforementioned ticket for examples of this error message.

The procedure for increasing the relevant system limits is as follows:
- Validate that the limits haven't already been increased
- If not, run, as root:

```
chsec -f /etc/security/limits -s default -a "rss=-1"
chsec -f /etc/security/limits -s default -a "nofiles=50000"
```
- Reboot the LPAR for the new limits to take effect.

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/6a4f37b1157d45ee74c4ca21f330c5e7163c6548
