### ISSUE TITLE
Dead link at https://docs.getchef.com/essentials_cookbook_metadata.html 

### ISSUE THREAD

**Issue by kungfujoe** [chef-boneyard/chef-web-docs-2016#422]
https://docs.getchef.com/essentials_cookbook_metadata.html has a dead link to http://docs.getchef.com/cookbook_repo.html.

404 Not Found

```
Code: NoSuchKey
Message: The specified key does not exist.
Key: cookbook_repo.html
RequestId: 6D27F4E8E1D39BB6
HostId: rJHAUPGKPpkj2fPhuY3zgzXOZ3kl3ojkMtWmYp5pnkknQdafH1uzaWnGSWKbgF8TTPBTCMMDnU4=
```

An Error Occurred While Attempting to Retrieve a Custom Error Document

```
Code: NoSuchKey
Message: The specified key does not exist.
Key: page_not_found.html
```

**Comment by PierreRambaud** [comment]
This link isn't dead anymore.

**Comment by jamescott** [comment]
Right. We had an issue last week for ~2 hours where a fair number of pages went 404. That was resolved quickly and all pages should be back online.
