### ISSUE TITLE
Clarification for AWS HA configuration prereqs. 

### ISSUE THREAD

**Issue by markan** [chef-boneyard/chef-web-docs-2016#424]
I found the text in chef-docs/includes_install/includes_install_server_ha_aws_pre.rst, section 5 "Decide on what IP address the backend virtual IP (VIP) will be..." to be a bit confusing. 

It's important that that address be eligible to be a 'Secondary Private IP Address'  as documented in http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/MultipleIP.html. I was confused and thought it was referring to an elastic IP, which doesn't work. 

Perhaps this paragraph should read:

Choose an IP address for the backend IP. It must reside in the same network segment as the backend machines, and be available to be assigned as a secondary private IP to the primary backend |chef server|. An AWS elastic IP will not work here. It will be specified in the |chef server rb| file; during installation, the high-availability plugin will automatically assign the secondary IP to the |amazon eni| for the primary instance.

@jamescott @juliandunn (Julian included because he's the one who sorted me out when I was trying to use an EIP, and I'd like for him to check that I understood things right.)

**Comment by juliandunn** [comment]
That sounds fine. We could write that a secondary elastic network interface IP is a completely different technology than an elastic IP (rather than "it doesn't work here") and link to the aforementioned documentation page at Amazon.

**Comment by jamescott** [comment]
First edit:

https://github.com/opscode/chef-docs/commit/db266f24dce22d1fd940aa5c13275c21f6fe495b
