### ISSUE TITLE
Some command line options for omnitruck install.sh are missing in the documentation

### ISSUE THREAD

**Issue by tknerr** [chef-boneyard/chef-web-docs-2016#429]
While working on a PR for a [related issue in Vagrant](https://github.com/mitchellh/vagrant/issues/4989), I noticed that the [`-d` and `-f` command line options](https://github.com/opscode/opscode-omnitruck/pull/33) of the omnitruck `install.sh` are not officially documented yet here:
https://docs.chef.io/install_omnibus.html

So what do they do?
- if neither `-d` or `-f` are specified the omnibus package is downloaded to a transient temp directory
- if `-d` (directory) is specified the omnibus package will be downloaded to that directory with its original filename being preserved
- if `-f` (path to filename) is specified the omnibus package will be downloaded to that specific filename

You can find a bit more detailed description in [the original PR](https://github.com/opscode/opscode-omnitruck/pull/33).

Mind adding these to the official docs?

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/83af87759f835f6b483279ea2e9ad92a3b75c93b

Slightly pedantic :) But should be OK for this iteration. Let me know if this works for you. And thanks!

**Comment by tknerr** [comment]
Thanks, that was fast! Looks good to me.

Btw: the `-s` option should be removed from the table imho, as it is not really an option that is passed to the install.sh script. It is actually [an option to the bash shell](https://www.gnu.org/software/bash/manual/html_node/Invoking-Bash.html) that is only needed in the 2nd example form (i.e. `curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -v 12.0.2`) so that bash interprets the remainder (=> the actual install.sh options) correctly.

**Comment by jamescott** [comment]
Let's get rid of the -s then:

https://github.com/opscode/chef-docs/commit/6ac3b4a8ca6ba1939d1e063b14ce15856dd0ff85
