### ISSUE TITLE
Syntax description inconsistency

### ISSUE THREAD

**Issue by hozumi** [chef-boneyard/chef-web-docs-2016#44]
http://docs.opscode.com/resource_package.html

``` ruby
package "name" do
  attribute "value" # see attributes section below
  ...
  action :action
end
```

The above syntax description confuses me, because there is no attribute named `attribute`.
I believe that `attribute` should be replaced with `some_attribute` or actual attribute.

**Comment by jamescott** [comment]
That's a good suggestion. I will make the change to some_attribute globally for all of the resource syntax examples. Thank you.

**Comment by hozumi** [comment]
Thanks!
