### ISSUE TITLE
knife ssl check refers to incorrect server certificate file location

### ISSUE THREAD

**Issue by jtimberman** [chef-boneyard/chef-web-docs-2016#440]
The **SSL certificate has invalid X.509 properties** section has this path:

```
  /var/opt/opscode/chef-server/nginx/ca/SERVER_HOSTNAME.crt
```

It should be this:

```
  /var/opt/opscode/nginx/ca/SERVER_HOSTNAME.crt
```

**Comment by jtimberman** [comment]
This is in these pages:
- https://docs.chef.io/knife_ssl_check.html
- https://docs.chef.io/chef_client_security.html

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/caa4b33d41f3132c06851cded26cb74d376bd72a

Thank you!
