### ISSUE TITLE
Machine run_list needs to be an array of strings

### ISSUE THREAD

**Issue by christinedraper** [chef-boneyard/chef-web-docs-2016#444]
https://docs.chef.io/resource_machine.html states that a run_list can be a comma separated list as follows:

'recipe[COOKBOOK::RECIPE],COOKBOOK::RECIPE,role[NAME]'

However, in the machine resource (unlike on the command line), the run_list must be an array of strings, e.g.:

[ 'recipe[COOKBOOK::RECIPE]','COOKBOOK::RECIPE','role[NAME]' ]

**Comment by jamescott** [comment]
Thank you Christine!

Here's the update:

https://github.com/chef/chef-docs/commit/acb36b962e69c91c34a5ba5f51308a4b668d751a
