### ISSUE TITLE
windows_service run_as_user, run_as_password undocumented

### ISSUE THREAD

**Issue by heathsnow** [chef-boneyard/chef-web-docs-2016#445]
I can see it in the code but not the documentation:
Code:
https://github.com/chef/chef/blob/8b37ebb3468879477fbeeba9511c10a00d530b97/lib/chef/resource/windows_service.rb
Docs:
https://docs.chef.io/resource_windows_service.html

**Comment by jamescott** [comment]
These attribute haven't been added to an official chef-client release. Yet! But I believe the next release is coming up fairly soon.

Will add them and version the docs at that time.

james

**Comment by jamescott** [comment]
Hi there, 

These attributes are part of the chef-client 12.1 release, which was released earlier this week. This commit gets these attributes into the current docs:

https://github.com/chef/chef-docs/commit/48cd9da7dcc9f92f40f9cd621d3780f66f1050db

Which are these topics:

https://docs.chef.io/resource_windows_service.html
https://docs.chef.io/release_notes.html

Once that commit is finished building ... (which is doing right now).

James

**Comment by michael-tam** [comment]
Has anyone been able to get the run_as_user or run_as_password to work for the windows_service resource?  When I tried to run it, the Log On information does not get updated when I look in the Windows Services console.
