### ISSUE TITLE
Unclear syntax for machine 'attribute' and 'attributes' attributes

### ISSUE THREAD

**Issue by christinedraper** [chef-boneyard/chef-web-docs-2016#446]
In the Attributes section of https://docs.chef.io/resource_machine.html , it is really not obvious how to use the 'attribute' and 'attributes' attributes.

I have figured out the former. 

machine 'fred' do
  attribute ['x', 'y', 'z'], value
end

is the equivalent of 
node.normal['x']['y']['z'] = value

The latter still eludes me.

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/b8ad8c0b9796d7289ed6f7af4a839f2b26c8862c

I had discussed this just before the holidays with John Keiser. The "SEE NOTES" under the attributes property was my clue :) All of the provisioning-related resources are still a work in progress.

Hopefully this makes them more clear. Use attributes to set 100% of the normal attributes you want to set on the node with a Ruby hash.
