### ISSUE TITLE
Machine resource actions are incorrect 

### ISSUE THREAD

**Issue by christinedraper** [chef-boneyard/chef-web-docs-2016#447]
The actions described in https://docs.chef.io/resource_machine.html don't match the current chef-provisioning code (as in chefdk 0.3.6). There is no :create action. The list of actions are:

nothing, allocate, ready, setup, converge, converge_only, destroy, stop

From what I can tell... 
'allocate' looks to be the closest to the previous 'create' - it makes sure an instance exists
'ready' makes sure the machine is running
'setup' puts chef, keys etc on the machine (bootstrap without a chef-client run)
'converge' does setup and chef-client run
'converge-only' just does chef-client run

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/185bb7290ee2c1fe4015a0ec9bb17b3c2c29a4d3

Gonna need to do some more research on these ones to get better descriptions :)

**Comment by jamescott** [comment]
OK, here's better descriptions for those actions:

https://github.com/chef/chef-docs/commit/259afe5459c497fec2fe7494de714c11ea065b3e
