### ISSUE TITLE
Documentation doesn't state chef_server_url needs "/organization/ORGNAME"

### ISSUE THREAD

**Issue by galenemery** [chef-boneyard/chef-web-docs-2016#450]
On: https://docs.chef.io/config_rb_knife.html

There is no mention that as of Chef Server 12, all references to chef_server_url will require an organization.

Client.rb has been updated appropriately: https://docs.chef.io/config_rb_client.html

**Comment by jamescott** [comment]
Depends on default_orgname setting in chef-server.rb, no?

http://docs.chef.io/upgrade_server_open_source_notes.html#organization-names

That said, an update:

https://github.com/chef/chef-docs/commit/3676703dc879f42c479e7c61118e4fe30c2dc52f

It's gonna work without it though, if the upgrade from Open Source >> 12 was done and that setting is valid.
