### ISSUE TITLE
Example output for  /organizations/NAME/cookbooks/_latest

### ISSUE THREAD

**Issue by thorduri** [chef-boneyard/chef-web-docs-2016#453]
The example output is essentially empty, see:

https://docs.chef.io/api_chef_server.html#cookbooks-latest

**Comment by jamescott** [comment]
Example was added.

**Comment by thorduri** [comment]
" thhe response is similar to:"

Cheers!

**Comment by jamescott** [comment]
Well ... :)

https://github.com/chef/chef-docs/commit/f3cd03b76ab062b909fc0fa5a22bb3ae41183827
