### ISSUE TITLE
Workstation setup documentation is somewhat confusing for Server 12

### ISSUE THREAD

**Issue by zts** [chef-boneyard/chef-web-docs-2016#465]
Someone flagged up on the IRC channel that the Workstation setup page here - http://docs.chef.io/client/install_workstation.html - is a bit confusing to someone setting up Chef Server 12 for the first time.

Looking at the section "Manually (w/o Webui)", the intro says we need to "create the ORGANIZATION-validator.pem and USER.pem files".  This is echoed in the next section "Create .chef Directory", and matches the rest of the Chef documentation.

The problems are...
- The "Create an Organization" section, which names the created key `/tmp/chef.key` (I'm not certain, but think this is the ORGANIZATION-validator.pem)
- The "Create a User" section, which names the created key `/tmp/grantmc.key` (I think this is the USER.pem)
- The "Create the knife.rb File" example, which uses `chef.pem` and `grantmc.pem` as filenames.

I don't have a Chef Server 12 handy to verify all this, so I can't readily make a pull request with the changes.  My suggestion would be to update the example filenames to match the `ORGANIZATION-validator.pem` and `USER.pem` format used throughout the documentation.

It might also be worth making it clear that the private key output by `chef-server-ctl org-create` is the organization validator.

**Comment by jamescott** [comment]
I made some edits to help improve the readability of that page, sync up the correct names, highlight the examples better:

https://github.com/chef/chef-docs/commit/2e85ccfcfbccaf4bb85764adb9e746f3d138c6e7
https://github.com/chef/chef-docs/commit/3b7a66e5b1829571d6f293a51b08b36cc5a7970a
https://github.com/chef/chef-docs/commit/3affc9ba4619a06a7b31283c988a50bc27ba123b

That's building now.

**Comment by jamescott** [comment]
... and this one:

https://github.com/chef/chef-docs/commit/6d63c6d40c3a6820121e91d12c0aeb8f904682c9
