### ISSUE TITLE
Link to the "file specificity" description from cookbook_file resource

### ISSUE THREAD

**Issue by nathenharvey** [chef-boneyard/chef-web-docs-2016#47]
The words "file specificity" on http://docs.opscode.com/resource_cookbook_file.html should link to http://docs.opscode.com/essentials_cookbook_files_specificity.html

**Comment by jamescott** [comment]
All of the file-based resources include the section for file specificity.

http://docs.opscode.com/resource_cookbook_file.html#file-specificity
