### ISSUE TITLE
Chef Subscription premium features should clearly be labeled as such on docs pages

### ISSUE THREAD

**Issue by mfdii** [chef-boneyard/chef-web-docs-2016#475]
This was brought up from a user of Open Source Chef. Any docs pages that describe the usage of a Chef Subscription feature (HA, Analytics, Reporting, etc) should clearly call out that this is a premium feature of a Subscription and not part of Open Source. 

A banner or header on the appropriate pages should suffice, and possibly linking to the [Chef Subscription](https://www.chef.io/chef/#plans-and-pricing) details page.

examples:
https://docs.chef.io/server_high_availability.html
http://docs.chef.io/analytics/

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/4fe75d42884059ec77026ceb3571ca169d019fc5

**Comment by mmzyk** [comment]
@jamescott Push Jobs, while installed as an add on, is not a premium feature. It's open source and free for as many nodes as the user wants, so that notice needs to be removed from all push jobs pages.

**Comment by mmzyk** [comment]
Also, @jamescott the DRDB HA is so not a premium feature. It is free for use. However, all other HA features (like aws) are premium.

**Comment by jamescott** [comment]
OK. Thank you. I believe this is all fixed and updated and I'm gonna close this one out.

james

**Comment by mfdii** [comment]
Thanks all.
