### ISSUE TITLE
pull chef-container / knife-container docs

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#481]
Hey James. I made the call to [abandon the work](https://github.com/chef/knife-container/pull/56) that had been done on `knife container` and all that -- it didn't really pan out for us as a thing. Can you remove this info from the docs?

**Comment by jamescott** [comment]
Part one: https://github.com/chef/chef-docs/commit/2501f47c95f9c0830885f2376a9ac4fab0d4c5e4

**Comment by jamescott** [comment]
Part two: https://github.com/chef/chef-docs/commit/5159bcbe9b0cae6a9ef14260cad3a9520c22e7cd

**Comment by jamescott** [comment]
Keep this one as a generic placeholder? Or remove?

http://docs.chef.io/containers.html

**Comment by juliandunn** [comment]
Let's just kill that for now too.

**Comment by jamescott** [comment]
Part three: https://github.com/chef/chef-docs/commit/f8e23b672da8262395de8f2e23d43af37e2ff5af

**Comment by jamescott** [comment]
And part four: https://github.com/chef/chef-docs/commit/e1191100b4b5f451160a4466423fe3f4ddf9524f

That should get it out of the docs, configure backup redirect behaviors, and so on.

**Comment by jamescott** [comment]
(part five, laggards): https://github.com/chef/chef-docs/commit/0463e210dcc89e79f0d85866167d38181e882241
