### ISSUE TITLE
Clarify which features are Enterprise-only and which are free in Chef 12, etc.

### ISSUE THREAD

**Issue by kwilczynski** [chef-boneyard/chef-web-docs-2016#482]
Hey @jamescott ,

I got a feedback from few people (including recently @predominant) that there isn't a decent table showing feature comparison and/or what is included for free and what is to be paid for (for example, _Chef Sync_ vs _High Availability_ (the _DRBD_ based, etc.). The information is scattered all over the place, which can be confusing. Also, clarifying the license would be helpful too.

What do you think, @jamescott?

Thanks in advance :+1:

**Comment by mmzyk** [comment]
@kwilczynski That's probably a good idea. Banners were added to all the docs pages for premium features but a central location would be helpful I think.

But what do you mean by clarifying the license? Is this about the 25 node limit for free use of premium features, or something else?

As far as licenses of the code, as far as I know Chef only uses two - open sourced code is under the Apache v2 license, all other code is All Rights Reserved.

**Comment by kwilczynski** [comment]
@mmzyk :+1: 

About the licenses/product features -- this is the page that seem to be confusing (as per feedback form users): https://www.chef.io/chef/#plans-and-pricing

Update: I am not entirely sure what is confusing there (probably I am biased, since I worked for Chef, so the pricing model is something I can spell out after being woken up in the middle of the night while being still half-alseep).

**Comment by jonong1972** [comment]
@kwilczynski There are discussions in the pipeline currently to address this problem. We totally agree that the table on  the Chef product page is completely confusing - and this will change. We are working with our  marketing, sales, exec, and ux team right now to find a solution on how to solve this problem.

Thanks for the feed back!  I will bring it up in our next meeting.

**Comment by jamescott** [comment]
I am going to close this out because it's not really a chef-docs issue, more of a chef.io issue (that @jonong1972 is working on).

**Comment by kwilczynski** [comment]
@jamescott there are two issues here:

1) chef.io;
2) docs.chef.io.

The (1) can be resolved by people looking after the main web site, but the (2) can be resolved by having a table of features free vs paid on docs.chef.io. Like @mmzyk said, it would be a good idea. Especially, since when I get user to tell me that they detest docs.chef.io with a passion because it's not possible to find information they want there, I get a bit concerned (thus, this very issue was a result of this) as I feel responsible for making things better.

So, let's make it a thing -- this table, shall we? Every little helps :)

**Comment by jamescott** [comment]
I don't want to discuss licensing, how to pay, what to pay for, what should be paid for, etc. on the docs page. I can link to the page that Jon is rebuilding once he's done.

**Comment by kwilczynski** [comment]
@jamescott the thing I was suggesting, was a simple table showing a list of features matrix - free vs premium, and perhaps sending people to respective sub-pages. Would be quiet handy. Nothing about fees, etc. But, it's your call, of course.

**Comment by jamescott** [comment]
Right. I'm gonna link to that after Jon has it built on the chef.io pages :)

**Comment by kwilczynski** [comment]
@jamescott got it. Thank you!
