### ISSUE TITLE
Server certificate setup should clarify use of intermediate certs 

### ISSUE THREAD

**Issue by pburkholder** [chef-boneyard/chef-web-docs-2016#484]
This doc,

  https://docs.google.com/document/d/1YES4HzOieXPJeMsfpI1kmYDWVmUq56J7b4puNUQb9V0/edit?usp=sharing

has highlighted the proposed change to https://docs.chef.io/server_security.html

I know at least one user for whom this change would have saved us a fair bit of time.  Thanks for taking into consideration.

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/a00af7f4213f85fe2d7947cf8d4c214bffc5c517

Should have this URL after it's built:

http://docs.chef.io/server_security.html#intermediate-certificates

**Comment by pburkholder** [comment]
:+1:
