### ISSUE TITLE
chef_gem and gem_package have new 'clear_sources' attribute

### ISSUE THREAD

**Issue by pburkholder** [chef-boneyard/chef-web-docs-2016#487]
In https://github.com/chef/chef/pull/2867 I've added a `clear_sources` attribute to gem_package, and chef_gem.

It defaults to 'false' to maintain the current behavior,

When set to 'true' chef_gem and gem_package will use only the specified 'source', and not attempt to use https://rubygems. org. 

@jamesc Is this how you handle PRs that require documentation updates, or is there another way?

--Peter

**Comment by pburkholder** [comment]
@jamescott How can I help get the docs updated to reflect this new attribute?  Thanks, Peter

**Comment by davidwrede** [comment]
@pburkholder, I verified that this content is in the docs, so I'm closing this issue out.
