### ISSUE TITLE
Setting path for Ohai::Config[plugin_path] needs documentation

### ISSUE THREAD

**Issue by pburkholder** [chef-boneyard/chef-web-docs-2016#489]
https://docs.chef.io/config_rb_client.html#ohai-settings doesn't include what's probably the most important setting. Should probably have something like:

| Setting | Description |
| `[Ohai::Config[:plugin_path]` | Array of paths to search for plugins. Typically you'll append your custom plugins to those distributed with Chef, e.g.: `Ohai::Config[:plugin_path] << '/etc/chef/ohai_plugins'` |

Might also want to mention at https://docs.chef.io/ohai_custom.html and https://docs.chef.io/ohai.html that /etc/chef/client.rb will need tweaking for user's custom plugins to be utilized.

Thanks,

Peter

**Comment by pburkholder** [comment]
(table didn't render, but I hope you get the picture)

**Comment by jamescott** [comment]
Is now added to the list of Ohai settings. Thanks!

http://docs.chef.io/config_rb_client.html#ohai-settings
