### ISSUE TITLE
Windows doc needs to reference or include Helpers info

### ISSUE THREAD

**Issue by dhoer** [chef-boneyard/chef-web-docs-2016#491]
Window doc https://docs.chef.io/windows.html is great, but it needs to reference or include:
https://docs.chef.io/dsl_recipe.html#helpers

Helpers is very hard to search for...

**Comment by jamescott** [comment]
Added to the page:

https://github.com/chef/chef-docs/commit/c520ef053406b1385726b6ca518e6aa29ca0439a

And the pages are rebuilding now. Thanks for letting me know!

james

**Comment by dhoer** [comment]
Sweet!
