### ISSUE TITLE
knife rackspace flags no longer up to date

### ISSUE THREAD

**Issue by miketheman** [chef-boneyard/chef-web-docs-2016#504]
https://docs.chef.io/plugin_knife_rackspace.html

Missing descriptions of `region`, and possibly more.

**Comment by jamescott** [comment]
http://docs.chef.io/plugin_knife_rackspace.html

I went through and re-checked the list of options and also added the network group of subcommands.

**Comment by miketheman** [comment]
Awesome! I think it might be helpful to show some examples on this page - I don't think there are many.

**Comment by miketheman** [comment]
Resolved in 0bbd7ce0106834a6916dce3c5d6bb724ecd403bd by sending the viewer to the source.
