### ISSUE TITLE
Some cron examples are not properly quoted.

### ISSUE THREAD

**Issue by e0da** [chef-boneyard/chef-web-docs-2016#51]
See [here](https://github.com/opscode/chef-docs/blob/master/step_resource/step_resource_cron_run_only_in_november.rst). There are several examples on the https://github.com/opscode/chef-docs/blob/master/chef_master/source/resource_cron.rst page where values that should be quoted like `*` and `1-5` are not, and so result in a syntax error and `4` respectively. :)

**Comment by jamescott** [comment]
Checked in fixed topics. Thanks for letting me know!

**Comment by jamescott** [comment]
(and now in the syntax section too!)
