### ISSUE TITLE
Add Tiered architecture layout diagram is missing from Tiered page

### ISSUE THREAD

**Issue by vinyar** [chef-boneyard/chef-web-docs-2016#514]
Image for tiered architecture is available here:
http://docs.chef.io/server_firewalls_and_ports.html#tiered

It should also be available/referenced here:
http://docs.chef.io/install_server_tiered.html

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/567e0f1fa26e95291d9418fa4bfe18f667c472b1

**Comment by vinyar** [comment]
:+1:
