### ISSUE TITLE
Install the Chef DK docs should contain Powershell section from https://github.com/chef/chef-dk#powershell

### ISSUE THREAD

**Issue by jobsolete** [chef-boneyard/chef-web-docs-2016#517]
http://docs.chef.io/install_dk.html#set-system-ruby is very helpful for *nix system users, but leaves out valuable information for Windows users that can be found here: https://github.com/chef/chef-dk#powershell

**Comment by jamescott** [comment]
Is resolved:

https://github.com/chef/chef-docs/commit/eb3e78014e00f3e6ee45909b3f389e46a1eb17d9
