### ISSUE TITLE
Resource quick reference

### ISSUE THREAD

**Issue by knuckolls** [chef-boneyard/chef-web-docs-2016#52]
I think a lot of people's lives would be improved if there were a single page in the documentation with all of the resource usage examples from the rest of the docs as a quick reference. It would be in alphabetical order, and could be searched with command-s. The available actions and a link to the more detailed resource documentation would be supplied alongside it.

**Comment by jamescott** [comment]
Yes, I agree. Having a list of examples in alphabetical order is useful. I will add that to the work queue.

For the moment, we do have a single Resource doc that can be searched that does contain all of the examples, only grouped by resource (and with all of the non-example content).

Here: http://docs.opscode.com/chef/resources.html

James

**Comment by jamescott** [comment]
I should have put a link to this topic ages ago: http://docs.getchef.com/resource_examples.html ... it's alphabetical by resource, filtered just for the examples.
