### ISSUE TITLE
remote_file is missing an extra (third) / for local file access

### ISSUE THREAD

**Issue by vinyar** [chef-boneyard/chef-web-docs-2016#521]
**Example:**
As per current docs - this code will break

``` ruby
  remote_file "/etc/opscode/#{file_name}" do
    source "file://etc/staging/#{file_name}"
  end
```

The working code is (note three ///):

``` ruby
  remote_file "/etc/opscode/#{file_name}" do
    source "file:///etc/staging/#{file_name}"
  end
```

**Documentation now:**
source:
Required. The location (URI) of the source file. This value may also specify HTTP (http://), FTP (ftp://), or local (file://) source file locations.

**Should be:**
file:/// (similar to the windows section)

Note: In my opinion this is a bug. Relevant chef file bug here:
https://github.com/chef/chef/issues/3371

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/e03f161d48e95826ea8bfe78d95a97e49f7c5b3b

is building.

**Comment by vinyar** [comment]
verified
