### ISSUE TITLE
LDAP settings page does not include system_adjective

### ISSUE THREAD

**Issue by Tech356** [chef-boneyard/chef-web-docs-2016#526]
The LDAP documentation page doesn't have the settings for `system_adjective`.

https://docs.chef.io/config_rb_server_optional_settings.html#ldap

The ldap portion of the page is looks like it is rendered from here:

https://github.com/chef/chef-docs/blob/master/includes_config/includes_config_rb_server_settings_ldap.rst

The enterprise server settings page has the setting:

https://github.com/chef/chef-docs/blob/master/includes_config/includes_config_rb_chef_server_enterprise_settings_ldap.rst

**Comment by jamescott** [comment]
I will need to investigate. The enterprise server settings page builds this one:

http://docs.chef.io/enterprise/config_rb_chef_server_enterprise_optional_settings.html#ldap

and it's for Enterprise Chef Server version 11.x whereas this page:

https://docs.chef.io/config_rb_server_optional_settings.html#ldap

is for the version 12 Chef server. There are some differences in the list of settings.

**Comment by Tech356** [comment]
For what it's worth, I have used the `ldap['system_adjective']` on a Chef 12 server and it works.

**Comment by jamescott** [comment]
It's a valid setting for Chef server 12, but only in the context of the management console:

https://github.com/chef/chef-docs/commit/87cabe4f16069dee8b81e2226a1ad8d7c51d1b03

Verified with engineering. Thanks for raising this issue. The update should be on the page shortly.
