### ISSUE TITLE
"Restart when a configuration is broken"

### ISSUE THREAD

**Issue by jblaine** [chef-boneyard/chef-web-docs-2016#53]
"Restart when a configuration is broken" block in http://docs.opscode.com/chef/resources.html makes no sense

**Comment by jamescott** [comment]
Right. It's mangled. Got separated from a related template block. Updated to:

By default, notifications are :delayed, that is they are queued up as they are triggered, and then executed at the very end of the Chef run. If you want to run an action immediately, use :immediately:

template "/etc/nagios3/configures-nagios.conf" do
  # other parameters
  notifies :run, "execute[test-nagios-config]", :immediately
end

# this will fail and prevent us from restarting nagios if we broke the config

execute "test-nagios-config" do
  command "nagios3 --verify-config"
  action :nothing
end

Good catch.

James
