### ISSUE TITLE
We should show people how to run ChefSpec

### ISSUE THREAD

**Issue by galenemery** [chef-boneyard/chef-web-docs-2016#539]
We ship ChefSpec w/ Chef-DK, but don't state how to run it.

In fact, the documentation on the ChefSpec repo states to run just straight "rspec", but since we don't put rspec into the path.. this doesn't work for ChefDK users.

Instead the correct approach is to use "chef exec rspec" as per Dan's comment here: https://github.com/chef/chef-dk/issues/18#issuecomment-48763430

Can we update this page of documentation (https://docs.chef.io/chefspec.html) to have a "how to run ChefSpec" section just like here, but with "chef exec" prepended for ChefDK users? https://github.com/sethvargo/chefspec#running-specs

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/3ba3140653fea9de87856088e5f29b779b6075c2

**Comment by galenemery** [comment]
+1 love it.

**Comment by charlesjohnson** [comment]
Resolved by 3ba3140
