### ISSUE TITLE
Misplaced paragraph on resources.html

### ISSUE THREAD

**Issue by jblaine** [chef-boneyard/chef-web-docs-2016#54]
This is the opening to the _apt_package_ resource explanation and seems to be misplaced as it is very general (http://docs.opscode.com/chef/resources.html#apt-package)

"A resource is a key part of a recipe that defines the actions that can be taken against a piece of the system. These actions are identified during each Chef run as the resource collection is compiled. Once identified, each resource (in turn) is mapped to a provider, which then configures each piece of the system."

**Comment by jblaine** [comment]
Ditto for http://docs.opscode.com/chef/resources.html#chef-gem opening paragraph

**Comment by jblaine** [comment]
Ditto for http://docs.opscode.com/chef/resources.html#easy-install-package opening paragraph

**Comment by jamescott** [comment]
Probably on all of the package-related resource topics. I'll check the rest of them for ya.

**Comment by jblaine** [comment]
Yeah, seems that way -- also http://docs.opscode.com/chef/resources.html#ips-package

Will stop reporting more.

**Comment by jamescott** [comment]
Should all be fixed now.
