### ISSUE TITLE
Fix Configuration File Directory Note

### ISSUE THREAD

**Issue by sean-horn** [chef-boneyard/chef-web-docs-2016#547]
The first note in http://docs.chef.io/config_rb_server.html  is mistaken. The correct directory for Enterprise Chef and Chef Server 12 is `/etc/opscode`, not `/etc/chef-server`.  Of recent versions, only Open Source Chef Server 11 had a configuration directory of `/etc/chef-server`

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/80ae1c07096c6a807cf4cff0b29f8bca4b38a2b5

**Comment by sean-horn** [comment]
Thanks, @jamescott !  Looks good. I'll close this now.
