### ISSUE TITLE
Explain the git resource's `checkout_branch` more clearly

### ISSUE THREAD

**Issue by danielsdeleo** [chef-boneyard/chef-web-docs-2016#552]
Cf. https://github.com/chef/chef/pull/3289

As I wrote there:

---

The git provider is designed to work two ways:
1. You want to always sync a particular commit (which can change over time based on use of attributes, etc.). In this case you identify what commit you want from the upstream repo using the `revision` property of the git resource. The git provider will locally maintain its own branch and force it to whatever commit you want. This way, if you want to switch from one branch to another, or only deploy certain tags (maybe you set with attributes or a data bag item), you just set the `revision` and the provider will always ensure you're on the correct commit by checking `git ls-remote` on the upstream repo.
2. You want to do a one-time checkout. Usually this happens when you're maintaining developers' laptops with Chef. In this case, you set `enable_checkout` to false which prevents the git provider from attempting to checkout master to master. This usage was sort of bolted on to the git provider after use case (1), so it's a bit unwieldy, I admit.

---

What we're seeing is some users come to believe that the `checkout_branch` option is what they should use to specify what branch/tag/commit they want the provider to sync. We should explain clearly that this is what `revision` is for, and `checkout_branch` is only applicable for use case (2) OR if the user has a branch named "deploy" on their upstream repo.

Also, we should document why we use a different branch and why it's good. I'll try to explain here:

Over time, the user may change the value of the `revision` attribute from one branch to another, or to a tag, or a specific commit SHA, and back. The user might even point set the revision attribute to a branch where history gets rewritten. So rather that just track a specific branch or do a "headless" checkout of a commit, the git provider maintains its own branch (which should be a branch that does NOT exist on your upstream repo). The provider is then free to forcibly checkout this branch to any commit, without screwing up the local history of an existing branch (e.g., master), which could cause problems or confusion later. The fact that the branch on the box is named "deploy" is pretty much irrelevant; if you use `git rev-parse` and `git ls-remote`, you will see that chef is syncing your code to exactly the right commit.

**Comment by iankronquist** [comment]
Thanks!

**Comment by jamescott** [comment]
First iteration:

https://github.com/chef/chef-docs/commit/9870bb229edfb1c6f40833a4f3ef5b000eede72e

Gonna do one more and then you all can take a look and see if these updates are what you were looking for, and then we can iterate until we're done.

james

**Comment by jamescott** [comment]
OK, the topics are updated. For example:

chef-client 11.16: http://docs.chef.io/release/11-16/resource_git.html
chef-client 12.2: http://docs.chef.io/release/12-2/resource_git.html
current: http://docs.chef.io/resource_git.html

Should be identical descriptions on all relevant pages.

Please let me know if this is good.

**Comment by danielsdeleo** [comment]
LGTM, @iankronquist ?

**Comment by iankronquist** [comment]
@danielsdeleo Thanks! I think that will help rectify a lot of people's confusion.

**Comment by danielsdeleo** [comment]
Ok, calling this one done. Please open a new ticket here if you have any other suggestions.

Thanks!

**Comment by jamescott** [comment]
Syncing the release notes that had the new attributes with our changes:

https://github.com/chef/chef-docs/commit/b379dccf184105725616080867733ad15f74ca1d

(missed that one on the previous pass)

james
