### ISSUE TITLE
chef-server policy endpoints aren't documented

### ISSUE THREAD

**Issue by pburkholder** [chef-boneyard/chef-web-docs-2016#563]
@danielsdeleo may need to help with this, but https://docs.chef.io/api_chef_server.html doesn't have documentation on the /policy_group and other policyfile endpoints.

Thanks,

Peter

**Comment by danielsdeleo** [comment]
I can either write something up in here or update the RAML in the server repo. Preference?

**Comment by jamescott** [comment]
Update the RAML in the server repo, send me the URL for it when finished. I will probably add something to the chef-docs API pages so they are doc'd until the new RAML-based pages are ready.

**Comment by mmzyk** [comment]
@tylercloke has recently updated all the RAML docs I believe @danielsdeleo, so probably want to check with him on the state of it and what's there now, so you don't accidentally update something that might be old.

**Comment by jamescott** [comment]
yeah, @tylercloke sent me the info he's got. I'm gonna make an update to the docs to placeholder this for the near term until the RAML API docs are ready.

**Comment by tylercloke** [comment]
:+1: Check with dan to make sure what is there is valid and go ahead an port that shiz until we have the RAML complete!

**Comment by danielsdeleo** [comment]
@jamescott @tylercloke The policies stuff is old and the APIs have been substantially revised since then. I'll try to get you an update today. Until then, the best place to look is at the pedant tests: https://github.com/chef/chef-server/blob/master/oc-chef-pedant/spec/api/policies/complete_endpoint_spec.rb These are a lot less factored than other pedant tests so they should be more readable.

**Comment by pburkholder** [comment]
Hmm:  https://docs.chef.io/api_chef_server.html still doesn't have the endpoints documented. Reopening.

**Comment by danielsdeleo** [comment]
I guess github got overzealous with the ticket linkage. But anyway, the RAML docs are good now so it's ready for the @jamescott treatment

**Comment by jamescott** [comment]
Updated release notes for Chef Server 12.1: http://docs.chef.io/release/server_12-1/release_notes.html

And also the root Chef Server API doc: http://docs.chef.io/api_chef_server.html

We'll have to keep working toward the full RAML solution, but this update gets things published for 12.1.
