### ISSUE TITLE
`chef shell-init` doc improvements for windows

### ISSUE THREAD

**Issue by danielsdeleo** [chef-boneyard/chef-web-docs-2016#565]
_NOTE:_ I imported this from https://github.com/chef/chef-dk/issues/448 there's a few bits that aren't relevant to chef-docs.

---

In the spirit of improving the Windows documentation... if you following the instructions for 'chef shell-init' literally on a clean Windows 8.1 machine with the latest ChefDK installed, the commands cannot be appended to $PROFILE because the folder does not exist if you have a new user profile.  The error given in that case is as follows:

```
PS C:\Users\Stuart> "chef shell-init powershell | Invoke-Expression" >> $PROFILE
out-file : Could not find a part of the path
'C:\Users\Stuart\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
At line:1 char:1
+ "chef shell-init powershell | Invoke-Expression" >> $PROFILE
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

One way around this is to use the following PowerShell instead of that suggested by 'chef shell-init'

``` powershell
if(Test-Path $PROFILE){ chef shell-init powershell | Add-Content $PROFILE } else { New-Item -Force -ItemType File $PROFILE; chef shell-init powershell | Add-Content $PROFILE }
```

This could be changed at https://github.com/chef/chef-dk/blob/master/lib/chef-dk/command/shell_init.rb#L49 

Additionally, if this is a new machine then it is also worth mentioning the execution of PowerShell scripts will not work until an administrator executes the following:

``` powershell
Set-ExecutionPolicy RemoteSigned
```

Neither of the above two points are mentioned at https://docs.chef.io/install_dk.html#powershell - additionally reference is made to a command 'posh' and I'm not sure where that comes from, certainly you can't run this on a Windows 8.1 or higher machine in out-of-box configuration.

![install_the_chef_dk_ _chef_docs](https://cloud.githubusercontent.com/assets/6384654/8466189/5a4f22a0-2050-11e5-8865-42472c0eec72.png)

This is in addition to https://github.com/chef/chef-dk/issues/429 that @smurawski raised a little while ago too.

**Comment by jamescott** [comment]
@danielsdeleo re: "posh" ... isn't that one of the supported command shells?

https://github.com/chef/chef-dk/blob/master/lib/chef-dk/command/shell_init.rb#L25

**Comment by danielsdeleo** [comment]
"posh" is just an abbreviation of "PowerShell"; we let you type `chef shell-init posh` so you can be lazy (like any good programmer :wink: ) but there isn't a command on the system called "posh" So I think what you want to write is something like

To try it in your current session:

``` posh
chef shell-init powershell | Invoke-Expression
```

For brevity, you can use "posh" as an abbreviation for "powershell":

``` posh
chef shell-init posh | Invoke-Expression
```

**Comment by jamescott** [comment]
OK, this fixes the posh issue:

https://github.com/chef/chef-docs/commit/32315c7bb3474b108304daad1db0765be02b2410

**Comment by danielsdeleo** [comment]
Thanks!

**Comment by jamescott** [comment]
This adds two examples for the admin and new profile issues:

https://github.com/chef/chef-docs/commit/22ff8866998d9c8e137292e7ab1579cc188491db

**Comment by danielsdeleo** [comment]
The above changes look good to me, and I think that takes care of everything that's relevant to chef-docs in this ticket. Thanks!
