### ISSUE TITLE
Windows File and Directory Deny Rights are incorrect

### ISSUE THREAD

**Issue by usepowershell** [chef-boneyard/chef-web-docs-2016#577]
Directory and File show examples of setting 

```
rights :deny, ['SomeUser']
```

This will error as :deny is not a valid option.

The correct syntax is 

```
deny_rights :read, ['SomeUser']
```

and deny_rights takes the same arguments as rights.

**Comment by jamescott** [comment]
This page is updated and fixed. Thanks for sending it in. (I found one more `deny` => `deny_rights` yesterday when I was validating before closing this out, fixed and rebuilt that change.)

Thanks Steven.
