### ISSUE TITLE
Create working examples of setting up Slack integration with Analytics's webhook feature

### ISSUE THREAD

**Issue by yvovandoorn** [chef-boneyard/chef-web-docs-2016#578]
As the title implies. 

Currently Analytics has a direct 'HipChat' feature under notifications inside of Analytics. This is great. However we should provide a working example of doing this with Slack as well. 

A working example gives those new to the Analytics webhook feature an ability to see how extensible it is and could spark (potentially) other integrations.

**Comment by jamescott** [comment]
http://docs.chef.io/analytics/release_notes.html#slack-incoming-webhooks

**Comment by yvovandoorn** [comment]
Hey James,

This is awesome. Should we put this else where (categorically) instead of
the release notes?

On Mon, Jul 27, 2015 at 10:04 AM, jamescott notifications@github.com
wrote:

> http://docs.chef.io/analytics/release_notes.html#slack-incoming-webhooks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chef/chef-docs/issues/578#issuecomment-125272966.

## 

_Yvo van Doorn_ — Manager, Solutions Architects

206.854.4666 – yvo@chef.io – *my: *Linkedin
http://www.linkedin.com/in/yvovandoorn/  Twitter
https://twitter.com/yvov

CHEF

CHEF.IO http://www.chef.io/

TM

_chef.io http://www.chef.io/_   Blog http://www.chef.io/blog/   Facebook
https://www.facebook.com/getchefdotcom   Twitter
https://twitter.com/chef   Youtube https://www.youtube.com/getchef

**Comment by jamescott** [comment]
well, it's in three places, actually:

http://docs.chef.io/analytics.html#slack
http://docs.chef.io/analytics/release_notes.html#slack-incoming-webhooks
http://docs.chef.io/plugin_knife_analytics.html#id15

I write it in once spot, then hook the same words in where it makes sense.

Those large images are being rebuilt to be smaller, FYI.

Thanks @mfdii also for the blog post.
