### ISSUE TITLE
Document how to run Windows as a scheduled task

### ISSUE THREAD

**Issue by pburkholder** [chef-boneyard/chef-web-docs-2016#586]
https://docs.chef.io/install_windows.html#run-as-a-service documents how to run as a service, but the consensus of Chef's own windows team is that a scheduled task is preferable [1].

We should document how to install as a scheduled task with random delay.  I'm willing to help.

1: https://getchef.zendesk.com/hc/en-us/articles/205233360

**Comment by jamescott** [comment]
I stubbed this in @pburkholder 

https://github.com/chef/chef-docs/blob/master/includes_ctl_chef_client/includes_ctl_chef_client_scheduled_task.rst

to get this started.

Would you mind taking a 2nd pass at it? Don't worry about breaking the topic, as it's not (yet) hooked into any specific builds. Either just note changes you'd want to see in this issue or do the full PR to the file should be fine.

**Comment by pburkholder** [comment]
@jamescott: Thanks for taking a first pass at this. Mike Tyler will be helping on a 2nd pass, but I think this is good enough for now.

**Comment by jamescott** [comment]
added to the install_windows.html topic
