### ISSUE TITLE
imports attribute of dsc_script only works with the code attribute

### ISSUE THREAD

**Issue by usepowershell** [chef-boneyard/chef-web-docs-2016#595]
chef-docs/includes_resources/includes_resource_dsc_script_attributes.rst  should reflect that the imports attribute only works with code attribute.  If a user uses the command attribute, then the user is responsible for creating any import-dscresource statements themselves.

**Comment by jamescott** [comment]
Hmm, well I didn't mean to "resolve and close" the bug. More like "does this added content resolve the bug?"

https://github.com/chef/chef-docs/commit/b7a81f2d409d6ef6436f2951f92fae07d4bedc2b

**Comment by usepowershell** [comment]
@jamescott Almost - the imports attribute will have no effect for the command attribute.
