### ISSUE TITLE
Analytics (1.1) installation instructions have an error

### ISSUE THREAD

**Issue by yvovandoorn** [chef-boneyard/chef-web-docs-2016#596]
Currently the instructions instruct someone standing up a standalone 1.1 Analytics server that the node_ip_address MUST be set to 0.0.0.0.

However when you do this, the Chef server (if using a standalone, single - not a backend) Chef server will no longer be able to connect to the local Chef server. You _need_ to specify a node_ip_address but instead of a value you leave it blank

The solution when you have a standalone Chef Server (e.g. no backend) and standalone Analytics server is:

`rabbitmq['node_ip_address'] = ''`

**Comment by jamescott** [comment]
@PrajaktaPurohit Can you verify the issue that Yvo is referring to?

**Comment by yvovandoorn** [comment]
Closing as the issue is related to the Subject Alternative Name being a required as of 1.1.4. The documentation on this portion is fine.
