### ISSUE TITLE
delay_mins is actually in seconds

### ISSUE THREAD

**Issue by gswallow** [chef-boneyard/chef-web-docs-2016#618]
Hi,

I configured a reboot resource (lol Windows) and set delay_mins to 2.  My boxes rebooted in two seconds.

I then reconfigured it, and got as scientific as timing it with a stopwatch, and sure enough it rebooted the Windows box in 60 seconds, like I told it to.

The file in question is chef-docs/swaps/swap_descriptions.txt.  I can submit a pull request if desired.

**Comment by mmzyk** [comment]
@gswallow PRs are always welcome and much appreciated.

**Comment by gswallow** [comment]
My point is, I can correct the docs, or the code.  Which would you prefer?

**Comment by mmzyk** [comment]
@gswallow Good point. I guess we do have the feature named delay_mins, which if we update the docs doesn't really do anything about the setting just being named confusingly. I'd suggest going for a PR against the code in this case, since the setting is just wrong. The client team can then give you more feedback on the PR once you submit it. If you haven't signed the CLA to contribute you'll need to do so, but once you submit the PR, Curry, one of our bots, will check if you have and direct you how to do so if you haven't.

Thanks!

**Comment by jamescott** [comment]
I think that first we should figure out if this is a bug in the reboot resource code:

https://github.com/chef/chef/blob/c91b3371036de811c9b2ba0e26f287e676dfd96f/lib/chef/platform/rebooter.rb#L35

Indicates to me that whatever the delay_mins integer is set to should *60. So '2' should be two minutes.

Either way, we need a doc update to clarify the reality of the setting. (I can do this, once we know for sure what the update should say.) And then we'll need another doc update (also, I can do) at the point when the reboot resource is updated. Figuring out if this is truly a bug requires engineers :)

**Comment by jamescott** [comment]
After talking with engineering, the setting is documented as it's **supposed** to work. The *60 should make delay_mins 2 = two minutes.

@gswallow if you can repro this, can you open an issue against the chef-client with the debug output and platform specifics so the engineers can investigate further?

**Comment by jamescott** [comment]
Also, may well be a bug in the code: https://technet.microsoft.com/en-us/library/Bb491003.aspx

**Comment by jamescott** [comment]
This change to the docs is building now:

https://github.com/chef/chef-docs/commit/409495bcf913d3f8abb7e9779860b9815a6bde9a

**Comment by jamescott** [comment]
I opened an issue against the chef repository: https://github.com/chef/chef/issues/3845

We can reopen this, depending on the outcome of that issue.
