### ISSUE TITLE
Ohai not returning memory information for Windows hosts

### ISSUE THREAD

**Issue by michael-tam** [chef-boneyard/chef-web-docs-2016#626]
Missing memory information for Windows systems.

There is a cookbook that uses an attribute file for a recipe that references node.memory.total and I get an error 'Undefined method or attribute `memory` on `node`'

**Comment by jamescott** [comment]
Hi Michael -- is this a documentation issue or an issue with Ohai and the Chef client?

**Comment by michael-tam** [comment]
An issue with Ohai and the Chef client, Ohai returns this information for Linux environments.

**Comment by jamescott** [comment]
Ah! Can you open this in https://github.com/chef/chef? That's where the software development for the Chef client is done (and it can trickle out to the Ohai repo from there).

If there's a related docs issue, we can revisit.
