### ISSUE TITLE
Double Quotes Needed...

### ISSUE THREAD

**Issue by hulu1522** [chef-boneyard/chef-web-docs-2016#628]
The following example is wrong and needs double quotes used instead of single quotes.

https://github.com/chef/chef-docs/blob/master/includes_ruby/includes_ruby_style_basics_string_embed_ruby.rst

This:

```
x = 'Bob'
'Hi, #{x}'      # => "Hi, Bob"
```

Should be:

```
x = 'Bob'
"Hi, #{x}"      # => "Hi, Bob"
```

**Comment by jamescott** [comment]
Ouch :)

Thanks for pointing that out. Here's the fix:

https://github.com/chef/chef-docs/commit/b08b661c8cf23150af3f9ed6d18a8aa1f4777035

and it's rebuilding.

**Comment by hulu1522** [comment]
Looks like you need to fix your patch... single quotes needed for the second example:

This:
`"Hello, #{x}"   # => "Hello, \#{x}" Notice that single quotes don't work with #{}`

Should be:
`'Hello, #{x}'   # => "Hello, \#{x}" Notice that single quotes don't work with #{}`

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/b8ce292fabeb01f5e9ec5d513769ebbd47b42a93

Double ouch? :)

**Comment by jamescott** [comment]
Resolved. Thank you!
