### ISSUE TITLE
Document attributes usage changes

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef-boneyard/chef-web-docs-2016#641]
Please add documentation coverage for the changes described in [RFC-23 chef 12 attributes changes](https://github.com/chef/chef-rfc/blob/master/rfc023-chef-12-attributes-changes.md).

There is some brief mention of the changes in the [Chef 12 Release Notes](http://docs.chef.io/release/12-0/release_notes.html#attribute-behavior-changes) but we should have more complete coverage of how to use the new functionality in the [Attributes Documentation](https://docs.chef.io/attributes.html). Especially the new methods for removing attributes.

**Comment by jamescott** [comment]
This is in the next build to the site.

**Comment by jamescott** [comment]
Updated:

https://docs.chef.io/attributes.html#change-attributes
