### ISSUE TITLE
copy paste error on https://docs.chef.io/server_users.html

### ISSUE THREAD

**Issue by Tech356** [chef-boneyard/chef-web-docs-2016#646]
In a few place the page says:

```
In the Leave Organization dialog box, confirm that the key should be regenerated
and click the Leave Organization button:
```

It probably should be something like

```
In the Leave Organization dialog box, confirm that you want to leave the organization
and click the Leave Organization button:
```

**Comment by jamescott** [comment]
thank you. good catch! I have submitted this update to our build pipeline.

james

**Comment by jamescott** [comment]
https://github.com/chef/chef-web-docs/commit/361ef5f651fa49b7bc8b2302769081bb0631c066

That should address the issue. Thank you for sending it in!
