### ISSUE TITLE
community guidelines link broken

### ISSUE THREAD

**Issue by christinedraper** [chef-boneyard/chef-web-docs-2016#650]
This link (which occurs in various places, including the 2015 Chef Summit page) 

https://docs.chef.io/community_guidelines.html

doesn't work any more - it instead ends up at https://docs.chef.io/plugin_community.html

**Comment by jamescott** [comment]
It was set to redirect, but should not have been. This has been fixed and now the correct page opens. Thank you for bringing this to my attention.

james
