### ISSUE TITLE
chef push jobs has outdated information on supported os

### ISSUE THREAD

**Issue by spuder** [chef-boneyard/chef-web-docs-2016#694]
> The Chef push jobs client can run on the following platforms:
> Ubuntu 10.04, 10.10, 12.04, and 12.10
> CentOS 5 and 6
> Microsoft Windows

https://docs.chef.io/push_jobs.html

Pretty sure it works on cent 7 and ubuntu 14.04 and newer

**Comment by davidwrede** [comment]
The latest version of this topic contains references to CentOS 7, Ubuntu 14.04, and Windows 10. We've also removed references to older, non-supported versions of Ubuntu.
