### ISSUE TITLE
Password for chef-server should be in single quotes

### ISSUE THREAD

**Issue by vinyar** [chef-boneyard/chef-web-docs-2016#712]
Page:
https://docs.chef.io/install_server.html

Bug 1: Password field should be in single quotes.
Special characters can cause shell to take action, for example !
Fix: place password into single quotes. (double quotes do not work)
`$ chef-server-ctl user-create user_name first_name last_name email 'password' --filename FILE_NAME`

Bug 2: "full_organization_name" should be in single quotes.
Fix: change double quotes to single quotes
`$ chef-server-ctl org-create short_name 'full_organization_name' --association_user user_name --filename ORGANIZATION-validator.pem
`

**Comment by jamescott** [comment]
Is updated. Thanks Alex!

**Comment by vinyar** [comment]
awesome! thanks @jamescott one day i'll learn how to make these updates myself
