### ISSUE TITLE
backup/restore documentation

### ISSUE THREAD

**Issue by sdarwin** [chef-boneyard/chef-web-docs-2016#719]
https://docs.chef.io/server_backup_restore.html

Restoration Section:

Many times (even most times?) when restoring, the entire server must be restored.  Does this procedure require that the new chef server be the same version as the old chef server?   It does not say.   then, any pointers about installing the same exact version of chef server?

**Comment by vinyar** [comment]
:+1:

**Comment by jamescott** [comment]
I added some clarification to the `chef-server-ctl restore` section, which is also being hooked into the page linked above. Starting with 12.2, when this command was introduced, it will restore data to any version of the Chef server 12.2 (and higher).

**Comment by jamescott** [comment]
Updated (4th bullet):

https://docs.chef.io/ctl_chef_server.html#restore
