### ISSUE TITLE
MSI installation has missing parameter

### ISSUE THREAD

**Issue by spuder** [chef-boneyard/chef-web-docs-2016#743]
There are 3 ADDLOCAL variables you can set when installing from an MSI
- ChefClientFeature
- ChefServiceFeature
- ChefPSModuleFeature

![screenshot 2015-11-03 14 17 37](https://cloud.githubusercontent.com/assets/242382/10922463/7ac1e6b8-8238-11e5-9d86-6b9dc6b2c8a9.png)

The documentation only references two of them. 

```
$ msiexec /qn /i C:\inst\chef-client-11.8.0-1.windows.msi ADDLOCAL="ChefClientFeature,ChefServiceFeature"
```

https://github.com/chef/chef-web-docs/search?utf8=%E2%9C%93&q=ChefClientFeature%2CChefServiceFeature

Instead of this:

```
msiexec /qn /i C:\inst\chef-client-11.8.0-1.windows.msi ADDLOCAL="ChefClientFeature,ChefServiceFeature"
```

it should be replaced with this

```
msiexec /qn /i C:\inst\chef-client-11.8.0-1.windows.msi ADDLOCAL="ChefClientFeature,ChefServiceFeature,ChefPSModuleFeature"
```

I'd edit this myself, however there is a bug on Mac OS X, with large git repos that causes them to take for ever to do a git clone. 10 minutes in, and git clone is still downloading.

**Comment by jamescott** [comment]
Hi there,

Belated thanks for the feedback. This change is in the build queue now. The chef-docs repo is indeed large.

james

**Comment by spuder** [comment]
@jamescott 
While the line in the documentation does now refer to all 3 parameters, it now references chef 11 instead of chef 12. Is that intentional? 

Before

```
  $ msiexec /qn /i C:\inst\chef-client-12.4.3-1-x86.msi ADDLOCAL="ChefClientFeature,ChefServiceFeature"
```

After

```
$ msiexec /qn /i C:\inst\chef-client-11.8.0-1.windows.msi ADDLOCAL="ChefClientFeature,ChefServiceFeature,ChefPSModuleFeature"
```

**Comment by jamescott** [comment]
:lol: ... I copied your line when I updated. Fixing now.

**Comment by jamescott** [comment]
Is updated.
