### ISSUE TITLE
knife.rb on windows has moved

### ISSUE THREAD

**Issue by spuder** [chef-boneyard/chef-web-docs-2016#747]
The documentation states that the default location chef looks for the knife.rb on windows is "~/chef-repo/.chef"

As of chefdk 0.7.0 that is no longer true.

https://docs.chef.io/config_rb_knife.html

https://www.chef.io/blog/2015/08/17/chefdk-0-7-0-released/

Now the default location is supposedly in `c:/users/foo/AppData/Local/chefdk`, however  I find that knife doesn't look there by default. 

```
Warning:
        ChefDK now defaults to using C:/Users/sowen/AppData/Local/chefdk instead of C:/Users/sowen/.chefdk.
        Since C:/Users/sowen/.chefdk exists on your machine, ChefDK will continue
        to make use of it. Please set the environment variable CHEFDK_HOME
        to C:/Users/sowen/.chefdk to remove this warning. This warning will be removed
        in the next major version bump of ChefDK.
INFO: Using configuration from C:/Users/sowen/.chef/knife.rb
```

Also supposedly chef looks at the location of `CHEFDK_HOME` however I find that isn't respected either. 

```
WARNING: No knife configuration file found
WARN: Failed to read the private key C:\chef\client.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - C:\chef\client.pem>
ERROR: Your private key could not be loaded from C:\chef\client.pem
Check your configuration file and ensure that your private key is readable
```

Please update the docs to show that ~/chef-repo is no longer the correct location for the knife.rb file, and document where windows should put the knife.rb file. As of right now it is very confusing.

**Comment by spuder** [comment]
I opened a support ticket with chef. The only location for chef home that works is `c:\Users\spuder\.chef`

**Comment by jamescott** [comment]
That bullet list item is updated to say:

"Is located by default at ~/chef-repo/.chef/knife.rb (UNIX and Linux platforms) or c:\Users\username.chef (Microsoft Windows platform, starting with Chef development kit version 0.7.0); use the --config option from the command line to change this location"

Thanks for sending in the feedback,

james

**Comment by spuder** [comment]
Great, I assume `c:\Users\username.chef` should be `c:\Users\username\chef`
