### ISSUE TITLE
Knife node documentation

### ISSUE THREAD

**Issue by jekriske** [chef-boneyard/chef-web-docs-2016#748]
https://docs.chef.io/knife_node.html#id21

Many examples on the knife node docs use both 'node' and 'node' instead of 'node' and 'NODE_NAME' or equivalent. It's unclear for users, if they just look at the examples, that they'd need to change the second 'node' entry.

Example:
`$ knife node run_list add node 'role[ROLE_NAME]'`

This should probably be
`$ knife node run_list add NODE_NAME 'role[ROLE_NAME]'`
or 
`$ knife node run_list add <node_name> 'role[ROLE_NAME]'`
etc.

The knife node docs are not consistent throughout the document. There are four different ways of referring to NODE_NAME:
- NODE_NAME
- node_name
- <node_name>
- node

**Comment by mabrahms-chef** [comment]
Hi jekriske. Thanks for the PR. There's a problem with incorporating PRs directly with Delivery right now, so I have incorporated your changes. Please do keep submitting PRs, though. Go to https://docs.chef.io/knife_node.html to see your changes.
