### ISSUE TITLE
consider putting a banner that Custom Resources are only available on Client >= 12.5

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#751]
The [custom resources](https://docs.chef.io/custom_resources.html) page doesn't say anywhere that it's only valid for Chef Client 12.5 and up. Because it is available right from the "Extend Chef" nav item, this is tripping people up. Can we add a banner at the top indicating this?

**Comment by jamescott** [comment]
adding

**Comment by thommay** [comment]
Or we should point people to https://github.com/chef-cookbooks/compat_resource for earlier 12s.

**Comment by jamescott** [comment]
adding a link to this ^^ cookbook

**Comment by jamescott** [comment]
added a link to the compat_resource cookbook:

https://docs.chef.io/custom_resources.html
