### ISSUE TITLE
registry_key resource: undocumented required key :data

### ISSUE THREAD

**Issue by stuartpreston** [chef-boneyard/chef-web-docs-2016#759]
https://docs.chef.io/resource_registry_key.html

Section: Delete a registry key value

Issue: Values array is missing a :data key from the value hash.  If :data is not specified then you get an error: `Missing data key in RegistryKey values hash` - see https://github.com/chef/chef/blob/master/lib/chef/resource/registry_key.rb#L89-L91

The two examples should be something like:

Use a double-quoted string:

```
registry_key "HKEY_LOCAL_MACHINE\\SOFTWARE\\path\\to\\key\\AU" do
  values [{
    :name => 'NoAutoRebootWithLoggedOnUsers',
    :type => :dword,
    :data => ''
    }]
  action :delete
end
```

or a single-quoted string:

```
registry_key 'HKEY_LOCAL_MACHINE\SOFTWARE\path\to\key\AU' do
  values [{
    :name => 'NoAutoRebootWithLoggedOnUsers',
    :type => :dword,
    :data => ''
    }]
  action :delete
end
```

**Comment by mabrahms-chef** [comment]
Hi stuartpreston. Thanks for the PR. There's a problem with incorporating PRs directly with Delivery right now, so I have incorporated your changes. Please do keep submitting PRs, though. Go to https://docs.chef.io/resource_registry_key.html to see your changes.
