### ISSUE TITLE
Clarify where to file bugs on the feedback page

### ISSUE THREAD

**Issue by thommay** [chef-boneyard/chef-web-docs-2016#760]
The feedback page (https://docs.chef.io/feedback.html) currently recommends that bugs should be filed on chef/chef, but that frequently results in issue triage just closing the bug and asking the submitter to refile in this repository, which is somewhat contributor hostile. I think in general we should point potential submitters here first and triage that way round.

**Comment by jamescott** [comment]
Updated:

https://docs.chef.io/feedback.html
