### ISSUE TITLE
"chef-server-ctl backup" is missing from documentation

### ISSUE THREAD

**Issue by vinyar** [chef-boneyard/chef-web-docs-2016#765]
URL: 
https://docs.chef.io/server_backup_restore.html
https://docs.chef.io/ctl_chef_server.html

Reference:
Chef server supports built in backup functionality via `chef-server-ctl backup` and `restore`
That functionality is not documented anywhere outside of command line help.

**Comment by vinyar** [comment]
@nweddle

**Comment by jamescott** [comment]
Updated:

https://docs.chef.io/server_backup_restore.html#chef-server-ctl
https://docs.chef.io/ctl_chef_server.html#backup
