### ISSUE TITLE
`openssl rand` for key generation?

### ISSUE THREAD

**Issue by ghost** [chef-boneyard/chef-web-docs-2016#77]
Why do the encrypted databag docs suggest using `openssl rand` for key generation when OpenSSL already ships with proper key management tools? A random sequence of bits isn't quite as secure as a proper key, is it? I've tested proper keys with encrypted data bags and they still work, so I can't imagine why the docs aren't pointing people at using proper keys.

**Comment by ghost** [comment]
Some discussion with coworkers yields that it's not actually a proper private key in the normal sense of public key crypto but rather the key for a symmetric cipher algorithm. The docs don't make this clear, and they should probably be updated.

**Comment by jamescott** [comment]
So thanks for the feedback. After some internal discussion, we updated the page: http://docs.opscode.com/essentials_data_bags.html#encrypt-a-data-bag ... the `openssl rand` isn't meant to imply a specific/recommended approach, but rather just show one way of getting started down a path for data bag encryption. Please let me know if this update gets at the question you were asking. James

**Comment by ghost** [comment]
On Mon, May 13, 2013 at 15:28:17 -0700 , jamescott wrote:

> So thanks for the feedback. After some internal discussion, we updated
> the page:
> http://docs.opscode.com/essentials_data_bags.html#encrypt-a-data-bag ...
> the `openssl rand` isn't meant to imply a specific/recommended
> approach, but rather just show one way of getting started down a path
> for data bag encryption. Please let me know if this update gets at the
> question you were asking. James

Thank you for taking the time to address this! The text about using a
random number does help. I guess I was confused by the use of the term
'secret key' which to me is something specific to public key crypto.
Adding text to clarify that the key chef uses isn't a key for public key
crypto would be useful - at least to people who think like I do. :)

Again, thank you for taking the time to look into this!

**Comment by jamescott** [comment]
Cool. I updated that page again (building right now -- refresh in ~10 mins and the changes should be there) to use the phrase "shared secret encryption" and a link to this page: https://en.wikipedia.org/wiki/Symmetric-key_algorithm. Same as last time -- please let me know if this helps. And any other feedback you have about any of the other docs. We're working hard on getting them all to be much better, one page at a time ;) James

**Comment by ghost** [comment]
On Mon, May 13, 2013 at 15:51:45 -0700 , jamescott wrote:

> Cool. I updated that page again (building right now -- refresh in ~10
> mins and the changes should be there) to use the phrase "shared secret
> encryption" and a link to this page:
> https://en.wikipedia.org/wiki/Symmetric-key_algorithm. Same as last time
> -- please let me know if this helps. And any other feedback you have
> about any of the other docs. We're working hard on getting them all to
> be much better, one page at a time ;) James

This looks good, thanks!

## 

Chris Nehren
