### ISSUE TITLE
service provider doc lacks systemd

### ISSUE THREAD

**Issue by kathyallen-okta** [chef-boneyard/chef-web-docs-2016#782]
Hello,
The doc https://docs.chef.io/resource_service.html#providers lacks reference to Chef::Provider::Service::Systemd.

thanks!

**Comment by jamescott** [comment]
Hi there! Thanks for mentioning this. A change has been pushed into our next build that will add systemd to the list of providers.

james

**Comment by jamescott** [comment]
This is updated. Thanks for the feedback!
