### ISSUE TITLE
Compliance api update

### ISSUE THREAD

**Issue by alexpop** [chef-boneyard/chef-web-docs-2016#786]
Please update this page:
  https://docs.chef.io/api_compliance.html

with this content:
  https://github.com/chef/chef-compliance/blob/master/docs/api_compliance.rst

**Comment by vinyar** [comment]
woot!! 👍

**Comment by vinyar** [comment]
Seems like this update has been made @alexpop

**Comment by alexpop** [comment]
Indeed, with a few more iterations since then :). Closing
