### ISSUE TITLE
chef_gem 'compile_time' wording isn't so great

### ISSUE THREAD

**Issue by jblaine** [chef-boneyard/chef-web-docs-2016#810]
https://docs.chef.io/resource_chef_gem.html

> compile_time
> 
> Ruby Types: TrueClass, FalseClass
> 
> Disable compile-time installation of gems. Recommended value: false. The chef-client will emit a warning when this setting is true. Use a respond_to? check to ensure backward compatibility. For example:
> 
> ...

IMO, should read something like:

> compile_time
> 
> Ruby Types: TrueClass, FalseClass
> 
> Control the stage of gem installation (compile-time or converge-time). Recommended value: false (therefore install the gem at converge-time). The chef-client will emit a warning when this setting is true. Use a respond_to? check to ensure backward compatibility. For example:
> 
> ...

**Comment by jmaziarz** [comment]
+1

**Comment by jamescott** [comment]
... and updated! Thanks again.

james
