### ISSUE TITLE
remove-partitions option to opscode-reporting-ctl should be documented

### ISSUE THREAD

**Issue by pburkholder** [chef-boneyard/chef-web-docs-2016#813]
The information in the KB article here, https://getchef.zendesk.com/hc/en-us/articles/205199230-How-Can-I-Clean-Up-Reporting-Disk-Space-Usage-, should be available also in https://docs.chef.io/ctl_reporting.html

Thanks, Peter

**Comment by jamescott** [comment]
adding this command to the list of options.
