### ISSUE TITLE
document block argument to load_current_value

### ISSUE THREAD

**Issue by bleything** [chef-boneyard/chef-web-docs-2016#814]
Today I was working on a resource that needed to run some commands in `load_current_value`, and those commands needed to have the property values from the resource loaded in. After some code spelunking I discovered that `load_current_value` can take a block argument and that it will pass in the new resource.

It would be super sweet if this was mentioned in the docs. Maybe save some folks some time!

**Comment by jkeiser** [comment]
@bleything note that any properties marked `desired_state: false` or `identity: true` will be passed implicitly to `load_current_value`--specifically, we will copy those values onto the `current_resource` before we invoke the block, so you can access them without needing the block argument. `desired_state: false` is the marker I generally use for "control properties" that aren't intrinsic to the resource but are important for retrieving the data, such as `retries` or `timeout`.

The block argument is there for when that's not enough--I haven't found the case yet, but I figure someone (perhaps you!) probably will!

**Comment by bleything** [comment]
@jkeiser: oh, cool, that's good to know. That's another thing that would be nice to have mentioned in the high-level docs... I was eventually able to find some info on available options for `property` by digging through the source, but it took longer than I would have liked. And I didn't see anything about those properties being injected into the `load_current_value` block.

Here's my specific use case: I'm writing a resource to manage rabbitmq users. To check whether the password needs to be updated, you run `rabbitmqctl authenticate_user <username> <password>`. So both of those need to end up inside the `load_current_value` block. The username is obviously an identity property, but the password is not. The password is definitely part of the desired state. I suppose I could force it by marking password as an identity property but I have no idea what else that would effect.

**Comment by jkeiser** [comment]
I actually agree password is desired state. I'm not entirely sure I understand the use case though--it doesn't seem like you can actually set `current_value.password` even if you want to, if they are different. I would have guessed it would be written something like this:

``` ruby
property :username, String, identity: true
property :password, String

# other properties ...
load_current_value do
  # load other properties
end

action :create do
  # Create or update the user's properties (not password)
  converge_if_changed do
    system("rabbitmqctl create_or_update_user #{username} --prop1 #{prop1} --prop2 #{prop2} ... ")
  end

  # If the user specified a password, and the password is not the same, do this:
  if property_is_set?(:password)
    if system("rabbitmqctl authenticate_user #{username} #{password}") != 0 do
      converge_by "Updating password for user #{username} ..." do
        system("rabbitmqctl update_user #{username} --password #{password}")
      end
    end
  end
end
```

**Comment by bleything** [comment]
What I've been doing is setting password to `nil` when the authentication fails, which will trigger a `converge_if_changed :password` block.

I do like the `property_is_set?` approach, and may have used it if I had known it existed, but it's also not in the docs :cry:

**Comment by jkeiser** [comment]
@bleythng not in the docs??? Argh. `reset_property` too. I <3 those methods. I hate nil checking, nil is sometimes a valid value! (Your use is fine.)

I see what you are doing, and that makes sense. It's fine to use the block arg as you are, all your choice :)

**Comment by jkeiser** [comment]
@jamescott ^^ `reset_property` and `property_is_set?`

**Comment by bleything** [comment]
I tend to hate nil checking too. My reasoning was that if the authentication fails, we don't know what the actual password is, and nil represents that concept neatly. It's fun when something you generally hate is actually the right thing to do!

Anyway, I'm glad that I'm not doing something horrible. It felt kinda wrong but that might have been because I had to go a'greppin' to figure out how to do it.

My original request for documentation on the block argument was kind of the most specific thing I could think of, but my overall experience has been that the custom resource docs are _very_ thin. Aside from the things we've discussed above, there's no mention of the other arguments you can pass to `property`, some of which are pretty handy. There's not even a link to the API docs where you can go find them yourself.

**Comment by jamescott** [comment]
Hi @bleything and @jkeiser -- here are first drafts for three sections to be added under "Advanced Options" (https://docs.chef.io/custom_resources.html#advanced-options):

load_current_value

https://github.com/chef/chef-web-docs/blob/master/includes_dsl_custom_resource/includes_dsl_custom_resource_method_load_current_value.rst

property_is_set?

https://github.com/chef/chef-web-docs/blob/master/includes_dsl_custom_resource/includes_dsl_custom_resource_method_property_is_set.rst

reset_property

https://github.com/chef/chef-web-docs/blob/master/includes_dsl_custom_resource/includes_dsl_custom_resource_method_reset_property.rst

I have a request right now in my inbox via the docs@chef.io feedback alias as well for some more info about the `provides` functionality.

james

**Comment by bleything** [comment]
Hey @jamescott! I like where these are going, but I was hoping for more detail for the `load_current_value` block form. Maybe something like:

> Any properties that are marked `identity: true` or `desired_state: false` will be available inside the `load_current_value` block. If you need to access other properties of your resource you can add a block argument which will contain all of the properties of the requested resource: <example goes here>

**Comment by jamescott** [comment]
@bleything Here's the latest: https://docs.chef.io/dsl_custom_resource.html ... `identity` and `desired_state` grouped under `property` along with a block argument.

**Comment by bleything** [comment]
Oh, sweet! That looks great!

**Comment by jamescott** [comment]
Glad to hear! I am gonna close this out as "resolved" but don't hesitate to raise new issues or reopen this one. Note that we moved the repo: https://github.com/chef/chef-web-docs ... it's a subtle change (note the `-2016` here); we removed the history from the repo to help improve our local build times :) (the commit history is quite large).

Thank you for raising this issue!

james
