### ISSUE TITLE
chef-shell seems undocumented

### ISSUE THREAD

**Issue by mattray** [chef-boneyard/chef-web-docs-2016#85]
http://wiki.opscode.com/display/chef/Shef probably just needs to be ported over

**Comment by jamescott** [comment]
docs.opscode.com/chef_shell.html

**Comment by mattray** [comment]
It's not linked from the front-page, could we add a link to chef-shell? Perhaps under "The Nodes"->"Tools"? It makes sense there and on the Workstation, but as long as it's linked at least one place that should help.

**Comment by jamescott** [comment]
Yes. Also, this (new) topic: http://docs.opscode.com/ctl_chef_shell.html.

**Comment by jamescott** [comment]
OK, done. Added the overview to Nodes/Workstations (Debug Recipes topic) and then the chef-shell (executable) under tools ... and also the Breakpoint resource: http://docs.opscode.com/resource_breakpoint.html

**Comment by mattray** [comment]
:+1:
