### ISSUE TITLE
cache_type and Moneta options are deprecated as of Chef 11.x

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#94]
Per discussion in HipChat, Chef 11.x no longer uses Moneta to do the local cookbook caching, so the "cache_type" directive in knife.rb (and client.rb) is deprecated.

http://docs.opscode.com/config_rb_knife.html (and friends)

In addition, reading the code, there seems to be a syntax_check_cache_path directive that will be used in preference to the old [:cache_options][:path] setting:

https://github.com/opscode/chef/blob/11.4.4/lib/chef/cookbook/syntax_check.rb#L53

This should be reflected in the documentation as well.

**Comment by jamescott** [comment]
fixed
